In [30]:
import pandas as pd


def read_in_chunks(file_object, chunk_size=1024, sep='*', header=None):
    csv_reader = pd.read_csv(file_object, sep=sep, iterator=True, chunksize=chunk_size, header=header)
    first_chunk = csv_reader.get_chunk()
    chunk = pd.DataFrame(first_chunk)
    for l in csv_reader:
        id = l.iloc[0,0]
        yield chunk
        chunk = pd.DataFrame(l)

chunk_iter = read_in_chunks("modified.csv", header=0)

for chunk in chunk_iter:
    print("_________")
    print(chunk.iloc[:,:1])
    
# df = pd.read_csv(
  #      'modified.csv',
  #  encoding = "ISO-8859-1",
  #  sep='*',
  #  engine='python',
  #  doublequote=True
#)

#df

_________
      C.COPYNO
0       228312
1        78769
2        78774
3        78777
4        78779
...        ...
1019     66791
1020     66808
1021     66809
1022     66829
1023     66830

[1024 rows x 1 columns]
_________
      C.COPYNO
1024    690621
1025     66849
1026    781000
1027     66866
1028     66876
...        ...
2043    720080
2044    680442
2045     65995
2046     65996
2047     66001

[1024 rows x 1 columns]
_________
      C.COPYNO
2048    892431
2049    429553
2050    648528
2051    648969
2052    510321
...        ...
3067     73741
3068     73755
3069     73769
3070     73781
3071     73798

[1024 rows x 1 columns]
_________
      C.COPYNO
3072    509713
3073     74024
3074    719004
3075    747192
3076     74035
...        ...
4091    628399
4092     78748
4093     78786
4094    648547
4095    513880

[1024 rows x 1 columns]
_________
      C.COPYNO
4096    479973
4097     88160
4098     77717
4099     87948
4100     77978
...        ...
5115    267729
5116     87256
5117    220274
5118     72827
5119     72828

[1024 rows x 1 columns]
_________
      C.COPYNO
5120     72833
5121    620004
5122    620002
5123    648797
5124     72839
...        ...
6139    775766
6140    770907
6141     82518
6142     82535
6143    509516

[1024 rows x 1 columns]
_________
      C.COPYNO
6144     82575
6145     83140
6146    694705
6147    694800
6148     82598
...        ...
7163    497652
7164    497653
7165    347874
7166    506132
7167    370574

[1024 rows x 1 columns]
_________
      C.COPYNO
7168     67063
7169     67059
7170     67060
7171     67089
7172    689635
...        ...
8187    710110
8188     84570
8189     64264
8190     87490
8191     87491

[1024 rows x 1 columns]
_________
      C.COPYNO
8192     87492
8193     87493
8194     87486
8195     87487
8196     87485
...        ...
9211     82632
9212     82678
9213     82726
9214     82729
9215     82731

[1024 rows x 1 columns]
_________
       C.COPYNO
9216      82847
9217      82860
9218      82885
9219      82889
9220      82961
...         ...
10235    680879
10236     65137
10237    508498
10238     59146
10239    538710

[1024 rows x 1 columns]
_________
       C.COPYNO
10240    495346
10241     59206
10242    711175
10243    711175
10244    711176
...         ...
11259    553400
11260    546201
11261    553393
11262    546202
11263    560325

[1024 rows x 1 columns]
_________
       C.COPYNO
11264    560330
11265    560331
11266    564946
11267    564947
11268    564967
...         ...
12283    530871
12284    530871
12285    429864
12286    429864
12287    868698

[1024 rows x 1 columns]
_________
       C.COPYNO
12288    868698
12289    450425
12290    522051
12291    537119
12292    528200
...         ...
13307     64241
13308    528080
13309    582733
13310    661302
13311    694373

[1024 rows x 1 columns]
_________
       C.COPYNO
13312    871240
13313    854363
13314    854363
13315     64359
13316     64345
...         ...
14331    526541
14332    526541
14333    525744
14334    525744
14335    552586

[1024 rows x 1 columns]
_________
       C.COPYNO
14336    552777
14337    552237
14338    552633
14339    552246
14340    552575
...         ...
15355    648923
15356    660965
15357    662621
15358    655299
15359    661313

[1024 rows x 1 columns]
_________
       C.COPYNO
15360    658487
15361    659363
15362    694366
15363    688832
15364    723148
...         ...
16379    400595
16380    170287
16381    553211
16382    553212
16383    182305

[1024 rows x 1 columns]
_________
       C.COPYNO
16384    682709
16385    682708
16386    610893
16387     59357
16388    720096
...         ...
17403     70296
17404     70322
17405     70347
17406     71645
17407    794879

[1024 rows x 1 columns]
_________
       C.COPYNO
17408    183865
17409    732640
17410    508721
17411    595420
17412    867237
...         ...
18427    544344
18428    553095
18429    621544
18430    621545
18431    661624

[1024 rows x 1 columns]
_________
       C.COPYNO
18432    688093
18433    754138
18434     73673
18435     73675
18436    848638
...         ...
19451    636855
19452    636856
19453    638434
19454    105996
19455    638433

[1024 rows x 1 columns]
_________
       C.COPYNO
19456     78896
19457    688943
19458    752381
19459    540743
19460    577824
...         ...
20475    692989
20476    692991
20477    648558
20478    183704
20479    183705

[1024 rows x 1 columns]
_________
      C.COPYNO
20480   183706
20481   183707
20482   183708
20483    75528
20484    75555
...        ...
21499   509683
21500   507155
21501    56841
21502    57028
21503    56857

[1024 rows x 1 columns]
_________
       C.COPYNO
21504    108097
21505    108098
21506    108099
21507    108100
21508    108101
...         ...
22523    745612
22524     85856
22525     85857
22526    370926
22527     63236

[1024 rows x 1 columns]
_________
       C.COPYNO
22528    370957
22529    219759
22530    192044
22531    192045
22532    192046
...         ...
23547     67103
23548    445724
23549    741223
23550     67112
23551    859892

[1024 rows x 1 columns]
_________
       C.COPYNO
23552    860234
23553     69637
23554    262415
23555    272755
23556    272755
...         ...
24571     62703
24572    410569
24573     62728
24574    137841
24575    200691

[1024 rows x 1 columns]
_________
       C.COPYNO
24576    532235
24577     62738
24578    543929
24579    543920
24580    543938
...         ...
25595    658961
25596    690180
25597    696738
25598    696739
25599    696774

[1024 rows x 1 columns]
_________
       C.COPYNO
25600    696778
25601    706794
25602    823017
25603    900665
25604    801999
...         ...
26619    822479
26620    822479
26621    503604
26622    527951
26623    546080

[1024 rows x 1 columns]
_________
       C.COPYNO
26624    565048
26625    822483
26626    822483
26627    750907
26628    750907
...         ...
27643    769735
27644    459358
27645     73092
27646    410720
27647    788677

[1024 rows x 1 columns]
_________
       C.COPYNO
27648    788678
27649    788679
27650    879355
27651    900599
27652     73243
...         ...
28667     73836
28668    222951
28669     73850
28670     73853
28671     73855

[1024 rows x 1 columns]
_________
       C.COPYNO
28672     73881
28673    826807
28674    826806
28675    826809
28676    826808
...         ...
29691     63531
29692    879339
29693    900734
29694     63578
29695     63601

[1024 rows x 1 columns]
_________
       C.COPYNO
29696     63602
29697     63626
29698     63628
29699     63629
29700    879949
...         ...
30715     71285
30716     71294
30717     71381
30718    527781
30719    182782

[1024 rows x 1 columns]
_________
       C.COPYNO
30720     71519
30721     71520
30722     83402
30723     71591
30724     71566
...         ...
31739    405414
31740     68300
31741     68355
31742     80468
31743    405413

[1024 rows x 1 columns]
_________
       C.COPYNO
31744    405413
31745     68427
31746     68496
31747     68526
31748     68295
...         ...
32763    182280
32764    182281
32765    182282
32766    182283
32767    182284

[1024 rows x 1 columns]
_________
       C.COPYNO
32768    182285
32769     68140
32770     68052
32771    800286
32772    829085
...         ...
33787     69672
33788     69678
33789     69666
33790     69676
33791    154939

[1024 rows x 1 columns]
_________
       C.COPYNO
33792    154940
33793     69719
33794    509676
33795    830068
33796    830069
...         ...
34811    528081
34812    694707
34813    902971
34814    902975
34815    902976

[1024 rows x 1 columns]
_________
       C.COPYNO
34816    476215
34817     70229
34818     70248
34819     70262
34820     70274
...         ...
35835    823273
35836    568918
35837    810571
35838    462769
35839    831265

[1024 rows x 1 columns]
_________
       C.COPYNO
35840    845188
35841    845189
35842    723698
35843    267746
35844    800194
...         ...
36859    547085
36860    554047
36861    559632
36862    559631
36863    559628

[1024 rows x 1 columns]
_________
       C.COPYNO
36864    559625
36865    559624
36866    561802
36867    565731
36868    573261
...         ...
37883      1919
37884      3259
37885      3335
37886      3336
37887      3338

[1024 rows x 1 columns]
_________
       C.COPYNO
37888      3339
37889      3345
37890      3488
37891      3481
37892      3491
...         ...
38907    715926
38908    805281
38909    805282
38910    684063
38911    701330

[1024 rows x 1 columns]
_________
       C.COPYNO
38912    701323
38913    701322
38914    701324
38915    701325
38916    791813
...         ...
39931    702701
39932    721310
39933    702702
39934    353839
39935    576882

[1024 rows x 1 columns]
_________
       C.COPYNO
39936    669557
39937    108095
39938    647797
39939    709528
39940    717265
...         ...
40955    575896
40956    669061
40957    657251
40958    701507
40959    701508

[1024 rows x 1 columns]
_________
       C.COPYNO
40960    815708
40961    723671
40962    889250
40963    619480
40964    753763
...         ...
41979    587193
41980    587194
41981    525585
41982    549198
41983    549699

[1024 rows x 1 columns]
_________
       C.COPYNO
41984    554020
41985    577604
41986    554022
41987    550751
41988    744760
...         ...
43003    601465
43004    601466
43005    601461
43006    601462
43007    601488

[1024 rows x 1 columns]
_________
       C.COPYNO
43008    601490
43009    601489
43010    601479
43011    601480
43012    601498
...         ...
44027    709536
44028    709535
44029    709534
44030    645573
44031    646489

[1024 rows x 1 columns]
_________
       C.COPYNO
44032    655402
44033    800965
44034    730526
44035    611768
44036    676208
...         ...
45051    529743
45052    529744
45053    529746
45054    529753
45055    529606

[1024 rows x 1 columns]
_________
       C.COPYNO
45056    529607
45057    529608
45058    529609
45059    529610
45060    529593
...         ...
46075    701382
46076    787054
46077    923418
46078    718938
46079    844146

[1024 rows x 1 columns]
_________
       C.COPYNO
46080    895262
46081    645845
46082    755236
46083    781992
46084    646061
...         ...
47099    562345
47100    562349
47101    563554
47102    582015
47103    580810

[1024 rows x 1 columns]
_________
       C.COPYNO
47104    580867
47105    577815
47106    587541
47107    587545
47108    591068
...         ...
48123    354480
48124    399476
48125    699080
48126     26699
48127     61283

[1024 rows x 1 columns]
_________
       C.COPYNO
48128    713184
48129     61298
48130    828866
48131    658707
48132     26741
...         ...
49147     78577
49148     78578
49149     78579
49150     78547
49151     78594

[1024 rows x 1 columns]
_________
       C.COPYNO
49152     78595
49153     78596
49154     78597
49155     78598
49156     78599
...         ...
50171     98094
50172     97235
50173     97243
50174     97269
50175     97281

[1024 rows x 1 columns]
_________
       C.COPYNO
50176     97465
50177     97457
50178     97455
50179     97452
50180     97445
...         ...
51195    219700
51196    219701
51197    219702
51198    219705
51199    219706

[1024 rows x 1 columns]
_________
       C.COPYNO
51200    219707
51201    219708
51202    219709
51203    219710
51204    219691
...         ...
52219    835566
52220    623168
52221    826310
52222    623092
52223    623094

[1024 rows x 1 columns]
_________
       C.COPYNO
52224    623170
52225    726104
52226    623173
52227    552368
52228    558119
...         ...
53243    364443
53244    547040
53245    547041
53246    364450
53247    364274

[1024 rows x 1 columns]
_________
       C.COPYNO
53248    364318
53249    364325
53250    271284
53251    426317
53252    784153
...         ...
54267    409711
54268    589672
54269    409713
54270    409570
54271    663380

[1024 rows x 1 columns]
_________
       C.COPYNO
54272    664344
54273    589674
54274    421574
54275    665063
54276    665064
...         ...
55291    636740
55292    677996
55293     21962
55294     21926
55295    693312

[1024 rows x 1 columns]
_________
       C.COPYNO
55296    542414
55297    881777
55298    590735
55299    561591
55300    723456
...         ...
56315    763385
56316    729849
56317    748329
56318    749084
56319    777960

[1024 rows x 1 columns]

_________
       C.COPYNO
56320    827230
56321    688357
56322    874423
56323    772502
56324    733424
...         ...
57339     34845
57340    173091
57341     86475
57342    742053
57343    633547

[1024 rows x 1 columns]
_________
       C.COPYNO
57344    705426
57345    825485
57346    512531
57347     34885
57348    831088
...         ...
58363    770612
58364    667296
58365    698628
58366    830897
58367    792248

[1024 rows x 1 columns]
_________
       C.COPYNO
58368    680155
58369    835643
58370    691310
58371    835538
58372    769524
...         ...
59387    526592
59388    526616
59389    526615
59390    526702
59391    526832

[1024 rows x 1 columns]
_________
       C.COPYNO
59392    526833
59393    532236
59394    531655
59395    537834
59396    540330
...         ...
60411    349752
60412      1249
60413      1253
60414      1252
60415      1256

[1024 rows x 1 columns]
_________
       C.COPYNO
60416    493512
60417    783527
60418    769423
60419    471269
60420    617837
...         ...
61435    895219
61436    853988
61437    895225
61438    853994
61439    895230

[1024 rows x 1 columns]
_________
       C.COPYNO
61440    853991
61441    895224
61442    854210
61443    853973
61444    895216
...         ...
62459    534117
62460    624214
62461    535542
62462    580088
62463    827542

[1024 rows x 1 columns]
_________
       C.COPYNO
62464    894394
62465    850557
62466    850556
62467    668222
62468    763564
...         ...
63483     13904
63484     13910
63485     13933
63486     14175
63487     14176

[1024 rows x 1 columns]
_________
       C.COPYNO
63488    866824
63489     13964
63490    679203
63491     14173
63492     14178
...         ...
64507    705475
64508     26002
64509     26063
64510     26067
64511     26072

[1024 rows x 1 columns]
_________
       C.COPYNO
64512    702468
64513    788284
64514    787853
64515     26099
64516    796425
...         ...
65531    657647
65532    520859
65533    539070
65534    540335
65535    714507

[1024 rows x 1 columns]
_________
       C.COPYNO
65536    857772
65537    847653
65538    586437
65539    593106
65540    586253
...         ...
66555    507340
66556    229186
66557     37736
66558     37738
66559     37740

[1024 rows x 1 columns]
_________
       C.COPYNO
66560    759020
66561    699839
66562    849577
66563    849578
66564    872538
...         ...
67579    601595
67580    525593
67581    601601
67582    601602
67583    613601

[1024 rows x 1 columns]
_________
       C.COPYNO
67584    601598
67585    601596
67586    601597
67587    601592
67588    783470
...         ...
68603    826592
68604      3447
68605    493504
68606    783564
68607    784005

[1024 rows x 1 columns]
_________
       C.COPYNO
68608      3448
68609    554952
68610    586566
68611      3520
68612    691378
...         ...
69627      9359
69628      9382
69629      9400
69630    909841
69631    614733

[1024 rows x 1 columns]
_________
       C.COPYNO
69632    683854
69633    677645
69634    833515
69635    755120
69636    506828
...         ...
70651    256483
70652    733656
70653    754933
70654    812741
70655    848449

[1024 rows x 1 columns]
_________
       C.COPYNO
70656    681424
70657     17583
70658    716581
70659     17608
70660     17609
...         ...
71675    656617
71676    704373
71677    830378
71678    759196
71679    582757

[1024 rows x 1 columns]
_________
       C.COPYNO
71680    183069
71681    708918
71682    691648
71683    192082
71684    598803
...         ...
72699    548063
72700    780585
72701    881988
72702    664420
72703    772263

[1024 rows x 1 columns]
_________
       C.COPYNO
72704    730824
72705    587824
72706    763409
72707    920968
72708    685208
...         ...
73723     34914
73724     34915
73725    548287
73726    721096
73727    590917

[1024 rows x 1 columns]
_________
       C.COPYNO
73728    796176
73729     34927
73730     34928
73731    656503
73732    137507
...         ...
74747    752475
74748    170858
74749    220466
74750    356161
74751    422611

[1024 rows x 1 columns]
_________
       C.COPYNO
74752    501904
74753    683536
74754    814267
74755    611447
74756    604051
...         ...
75771    924289
75772    849695
75773    385402
75774      8353
75775    423171

[1024 rows x 1 columns]
_________
       C.COPYNO
75776     46720
75777    559246
75778    223122
75779    831473
75780    789352
...         ...
76795    817745
76796    850863
76797    217114
76798    217107
76799    691350

[1024 rows x 1 columns]
_________
       C.COPYNO
76800    691351
76801    691349
76802    691353
76803    691354
76804    691352
...         ...
77819     11043
77820     11054
77821    713357
77822    880292
77823    438676

[1024 rows x 1 columns]
_________
       C.COPYNO
77824    645648
77825    679745
77826    743665
77827     11080
77828     12753
...         ...
78843    903757
78844    175228
78845    629293
78846    631460
78847    634584

[1024 rows x 1 columns]
_________
       C.COPYNO
78848    370988
78849     21916
78850    781560
78851    661826
78852     21947
...         ...
79867    781064
79868    816445
79869    668701
79870    609620
79871    808485

[1024 rows x 1 columns]
_________
       C.COPYNO
79872    567965
79873    568823
79874    730896
79875    755101
79876    659643
...         ...
80891    187289
80892    187293
80893    153621
80894    143905
80895    187268

[1024 rows x 1 columns]
_________
       C.COPYNO
80896    143967
80897    146130
80898    146129
80899    153602
80900    181838
...         ...
81915    145618
81916    145546
81917    145543
81918    145564
81919    145506

[1024 rows x 1 columns]
_________
       C.COPYNO
81920    145595
81921    145611
81922    145632
81923    145666
81924    145669
...         ...
82939    168837
82940    906419
82941    668440
82942    137946
82943     33537

[1024 rows x 1 columns]
_________
       C.COPYNO
82944    669688
82945    233193
82946    348019
82947    839788
82948    839824
...         ...
83963    915486
83964    169179
83965    896098
83966    668582
83967    561310

[1024 rows x 1 columns]
_________
       C.COPYNO
83968    560556
83969    741061
83970    170497
83971    169186
83972    890434
...         ...
84987    511451
84988    512570
84989    385981
84990    738904
84991    183399

[1024 rows x 1 columns]
_________
       C.COPYNO
84992    183400
84993    183401
84994    881489
84995    871218
84996    899144
...         ...
86011    187681
86012    187686
86013    187692
86014    187696
86015    187703

[1024 rows x 1 columns]
_________
       C.COPYNO
86016    187706
86017    187707
86018    187708
86019    187709
86020    532517
...         ...
87035    813207
87036    502867
87037    171156
87038    171157
87039    741060

[1024 rows x 1 columns]
_________
       C.COPYNO
87040    171164
87041    171165
87042    171166
87043    171167
87044    171168
...         ...
88059    229744
88060    781906
88061    623347
88062    892236
88063    736599

[1024 rows x 1 columns]
_________
       C.COPYNO
88064    824404
88065    716309
88066    630127
88067    912159
88068    906076
...         ...
89083    872798
89084    833433
89085    846398
89086    672736
89087    736570

[1024 rows x 1 columns]
_________
       C.COPYNO
89088    731589
89089    713189
89090    218730
89091    691163
89092    646000
...         ...
90107    831060
90108    700695
90109    700698
90110    700699
90111    906906

[1024 rows x 1 columns]
_________
       C.COPYNO
90112    566032
90113    747329
90114    392830
90115    655257
90116    741579
...         ...
91131    642153
91132    658453
91133    474203
91134    526797
91135    606815

[1024 rows x 1 columns]
_________
       C.COPYNO
91136    638860
91137    613101
91138    835022
91139    773858
91140    745904
...         ...
92155    883560
92156    883561
92157    735520
92158    735521
92159    723364

[1024 rows x 1 columns]
_________
       C.COPYNO
92160    797690
92161    799252
92162    799460
92163    553540
92164    780502
...         ...
93179    669190
93180    668762
93181    750027
93182    766545
93183    785757

[1024 rows x 1 columns]
_________
       C.COPYNO
93184    785758
93185    642124
93186    705749
93187    558978
93188    223217
...         ...
94203    663349
94204    663373
94205     13875
94206    610675
94207    612683

[1024 rows x 1 columns]
_________
       C.COPYNO
94208    629024
94209     13892
94210    369091
94211    393014
94212    393016
...         ...
95227    802705
95228    490484
95229    816985
95230    677945
95231    551925

[1024 rows x 1 columns]
_________
       C.COPYNO
95232    809157
95233    677426
95234    631819
95235    851283
95236    680385
...         ...
96251    784901
96252    793824
96253    784800
96254    793834
96255    922746

[1024 rows x 1 columns]
_________
       C.COPYNO
96256    784855
96257    784865
96258    784873
96259    784880
96260    784891
...         ...
97275    423193
97276    920369
97277    920370
97278    655598
97279    473865

[1024 rows x 1 columns]
_________
       C.COPYNO
97280    512415
97281    522979
97282    782080
97283    416508
97284     17540
...         ...
98299    844081
98300    131349
98301    135612
98302    220162
98303    778630

[1024 rows x 1 columns]
_________
       C.COPYNO
98304    729125
98305    813722
98306    636219
98307    136094
98308    136096
...         ...
99323    599015
99324    545541
99325    702051
99326    554321
99327    763255

[1024 rows x 1 columns]
_________
        C.COPYNO
99328     769864
99329     919473
99330     899515
99331     850101
99332     547116
...          ...
100347    803764
100348    804868
100349    807314
100350    809539
100351    790806

[1024 rows x 1 columns]
_________
        C.COPYNO
100352    782893
100353    871038
100354    809537
100355    763884
100356    731716
...          ...
101371    845929
101372    685957
101373    648316
101374    648403
101375    648379

[1024 rows x 1 columns]
_________
        C.COPYNO
101376    648898
101377    533080
101378    691721
101379    745632
101380    648413
...          ...
102395    748840
102396    891923
102397    692219
102398    787897
102399    822292

[1024 rows x 1 columns]
_________
        C.COPYNO
102400    862378
102401    902747
102402    880204
102403    688366
102404    840425
...          ...
103419    746856
103420     26628
103421    445931
103422    734620
103423    564496

[1024 rows x 1 columns]
_________
        C.COPYNO
103424    860394
103425    173398
103426    173397
103427     60945
103428    808867
...          ...
104443    882972
104444    708963
104445    747246
104446    760571
104447    612590

[1024 rows x 1 columns]
_________
        C.COPYNO
104448    635984
104449    633328
104450    633330
104451    624097
104452    882957
...          ...
105467    715206
105468    816048
105469    877621
105470     41636
105471     41674

[1024 rows x 1 columns]
_________
        C.COPYNO
105472     41703
105473     41716
105474     41753
105475     41808
105476     41856
...          ...
106491    347183
106492    347207
106493    501853
106494    329876
106495    143815

[1024 rows x 1 columns]
_________
        C.COPYNO
106496    164457
106497    136698
106498    137411
106499    139815
106500    136664
...          ...
107515    870654
107516    761442
107517    632648
107518    738962
107519    719789

[1024 rows x 1 columns]
_________
        C.COPYNO
107520    797656
107521    708042
107522    734311
107523    717351
107524    779077
...          ...
108539     88207
108540    754761
108541    753691
108542    746068
108543    761671

[1024 rows x 1 columns]
_________
        C.COPYNO
108544     88108
108545    238354
108546    359994
108547    775121
108548    557395
...          ...
109563    567446
109564    567448
109565    567449
109566     26933
109567     26937

[1024 rows x 1 columns]
_________
        C.COPYNO
109568    642846
109569     26956
109570    762043
109571    697086
109572     26995
...          ...
110587     38755
110588     38759
110589     38764
110590    133633
110591    547303

[1024 rows x 1 columns]
_________
        C.COPYNO
110592    581313
110593    606211
110594    547312
110595    581314
110596    606212
...          ...
111611    526004
111612    530011
111613    642465
111614    348911
111615    663875

[1024 rows x 1 columns]
_________
        C.COPYNO
111616    340416
111617    740302
111618    723404
111619    689469
111620    803139
...          ...
112635    787570
112636    792766
112637    732318
112638    737507
112639    793675

[1024 rows x 1 columns]
_________
        C.COPYNO
112640    796152
112641    592897
112642    593457
112643    626148
112644    527242
...          ...
113659    738335
113660    729385
113661    647193
113662    882388
113663    765988

[1024 rows x 1 columns]

_________
        C.COPYNO
113664    873228
113665    690801
113666    636752
113667    677986
113668    746076
...          ...
114683     20826
114684    759146
114685     20862
114686    782035
114687    792245

[1024 rows x 1 columns]
_________
        C.COPYNO
114688    923702
114689    628201
114690    345918
114691    673298
114692    519829
...          ...
115707    816127
115708    816128
115709    694320
115710     34157
115711     34115

[1024 rows x 1 columns]
_________
        C.COPYNO
115712     34131
115713     34221
115714     34246
115715     34274
115716     34313
...          ...
116731    526709
116732    526718
116733    526712
116734    526717
116735    526724

[1024 rows x 1 columns]
_________
        C.COPYNO
116736    526722
116737    526742
116738    526745
116739    526747
116740    529137
...          ...
117755    165309
117756    173350
117757    388453
117758    181600
117759    173023

[1024 rows x 1 columns]
_________
        C.COPYNO
117760    189996
117761    191230
117762    267185
117763    137107
117764    333305
...          ...
118779    555565
118780    555566
118781    643614
118782    547031
118783    809599

[1024 rows x 1 columns]
_________
       C.COPYNO
118784   586068
118785   604857
118786   384688
118787   351893
118788   173099
...         ...
119803   697668
119804   793697
119805   634155
119806   638849
119807   793172

[1024 rows x 1 columns]
_________
        C.COPYNO
119808    705656
119809    713634
119810    721182
119811    724696
119812    762445
...          ...
120827     51606
120828    801765
120829    844370
120830    598187
120831    579095

[1024 rows x 1 columns]
_________
        C.COPYNO
120832    607004
120833    607006
120834    634156
120835    867361
120836    633220
...          ...
121851    569383
121852     17104
121853     17105
121854     17106
121855     17107

[1024 rows x 1 columns]
_________
        C.COPYNO
121856     17110
121857     17113
121858    403800
121859     20961
121860     20963
...          ...
122875     37590
122876     37617
122877     37620
122878     37672
122879     37636

[1024 rows x 1 columns]
_________
        C.COPYNO
122880     37734
122881     38159
122882     37707
122883     37772
122884     37823
...          ...
123899     52628
123900     52634
123901     52631
123902     52639
123903     46750

[1024 rows x 1 columns]
_________
        C.COPYNO
123904    607531
123905     46754
123906     46758
123907     46796
123908    501655
...          ...
124923    781665
124924    586736
124925    586600
124926    587211
124927    586179

[1024 rows x 1 columns]
_________
        C.COPYNO
124928    586159
124929    586156
124930    586160
124931    586161
124932    592842
...          ...
125947    651151
125948    651215
125949    651217
125950    688436
125951    656757

[1024 rows x 1 columns]
_________
        C.COPYNO
125952    656759
125953    712132
125954    809002
125955    833004
125956    833966
...          ...
126971    522378
126972    522382
126973    528232
126974    528238
126975    528236

[1024 rows x 1 columns]
_________
        C.COPYNO
126976    529114
126977    527866
126978    529349
126979    540739
126980    533862
...          ...
127995    134841
127996    134838
127997     30158
127998     68285
127999    770154

[1024 rows x 1 columns]
_________
       C.COPYNO
128000    30232
128001    30246
128002    30306
128003   835745
128004    30416
...         ...
129019    44730
129020    44756
129021   528096
129022    44782
129023   138555

[1024 rows x 1 columns]
_________
       C.COPYNO
129024   833080
129025   833081
129026   911192
129027    44825
129028   582294
...         ...
130043   890984
130044   889434
130045   848793
130046   876253
130047   873937

[1024 rows x 1 columns]
_________
        C.COPYNO
130048    471066
130049    648133
130050     70965
130051    343263
130052    343728
...          ...
131067    740176
131068    797670
131069    535983
131070    820262
131071    820263

[1024 rows x 1 columns]
_________
        C.COPYNO
131072    820270
131073    722899
131074    776635
131075    820272
131076    820293
...          ...
132091    552726
132092    419511
132093    709129
132094    605691
132095    416915

[1024 rows x 1 columns]
_________
        C.COPYNO
132096    603321
132097    863413
132098    532467
132099    465067
132100    465083
...          ...
133115    641315
133116    733956
133117    825667
133118     13536
133119    767446

[1024 rows x 1 columns]
_________
        C.COPYNO
133120    729666
133121    641324
133122    734002
133123    745806
133124    636269
...          ...
134139    741254
134140    670665
134141    741289
134142    529373
134143    647892

[1024 rows x 1 columns]
_________
                    C.COPYNO
134144                741309
134145                647916
134146     333.912 C718i v11
134147  333.912 C718i v11 e2
134148                741291
...                      ...
135163                339455
135164                339543
135165                339570
135166                340290
135167                340514

[1024 rows x 1 columns]
_________
        C.COPYNO
135168    340537
135169    340544
135170    545467
135171    666602
135172     29300
...          ...
136187     41035
136188     41037
136189     41038
136190     41053
136191    766243

[1024 rows x 1 columns]
_________
        C.COPYNO
136192    669699
136193    619923
136194     41075
136195    663815
136196    664258
...          ...
137211    755990
137212    860470
137213    891850
137214    896799
137215    755935

[1024 rows x 1 columns]
_________
        C.COPYNO
137216    757504
137217    703392
137218    892586
137219    476145
137220    501437
...          ...
138235    181961
138236    150813
138237    181578
138238    171959
138239    198804

[1024 rows x 1 columns]
_________
        C.COPYNO
138240    162322
138241    161912
138242    143964
138243    146228
138244    146227
...          ...
139259    174813
139260    174814
139261    400471
139262    174824
139263    407276

[1024 rows x 1 columns]
_________
        C.COPYNO
139264    155039
139265    584297
139266    599598
139267    154958
139268     92530
...          ...
140283    659682
140284     26525
140285    777311
140286    642083
140287     26559

[1024 rows x 1 columns]
_________
        C.COPYNO
140288     26561
140289     26564
140290     26567
140291    628943
140292     26600
...          ...
141307     45978
141308    133559
141309     46061
141310    684017
141311    684018

[1024 rows x 1 columns]
_________
        C.COPYNO
141312     46100
141313    581909
141314    340136
141315    494395
141316    526096
...          ...
142331    814127
142332    814822
142333    814967
142334    654590
142335    853256

[1024 rows x 1 columns]
_________
        C.COPYNO
142336    742557
142337    654592
142338    653430
142339    653431
142340    653432
...          ...
143355    850670
143356    908104
143357    692249
143358    670742
143359    840339

[1024 rows x 1 columns]
_________
        C.COPYNO
143360    840340
143361    840343
143362    884838
143363    690695
143364    643882
...          ...
144379     29523
144380    922097
144381    651246
144382    855492
144383    431870

[1024 rows x 1 columns]
_________
        C.COPYNO
144384     29259
144385     29536
144386     29539
144387     29681
144388     29557
...          ...
145403     46247
145404    400817
145405    400818
145406     46192
145407    400819

[1024 rows x 1 columns]
_________
        C.COPYNO
145408     46274
145409    250917
145410     46464
145411     46423
145412     46495
...          ...
146427     49465
146428     49490
146429    398046
146430    473949
146431    494907

[1024 rows x 1 columns]
_________
        C.COPYNO
146432    496155
146433    521535
146434    166304
146435    528126
146436    531816
...          ...
147451    363640
147452    333683
147453    354654
147454    339415
147455    355370

[1024 rows x 1 columns]
_________
        C.COPYNO
147456    339405
147457    392032
147458    392036
147459    231412
147460    198628
...          ...
148475    504951
148476    502090
148477    502088
148478    501897
148479    514257

[1024 rows x 1 columns]
_________
        C.COPYNO
148480    526240
148481    528551
148482    528196
148483    528197
148484    538142
...          ...
149499    836394
149500    652731
149501    755187
149502    807341
149503    807343

[1024 rows x 1 columns]
_________
        C.COPYNO
149504    815831
149505    818695
149506    607955
149507    815334
149508    759136
...          ...
150523    189423
150524    773555
150525    773560
150526    772725
150527    772724

[1024 rows x 1 columns]
_________
        C.COPYNO
150528    668523
150529    772723
150530    799262
150531    799263
150532    799264
...          ...
151547    747799
151548    812406
151549    824480
151550    834414
151551    764518

[1024 rows x 1 columns]
_________
        C.COPYNO
151552    764519
151553    812413
151554    831573
151555    790345
151556    812456
...          ...
152571    841573
152572    911970
152573    709328
152574    709367
152575    722843

[1024 rows x 1 columns]
_________
        C.COPYNO
152576    769111
152577    825553
152578    694981
152579    694982
152580    919100
...          ...
153595    475600
153596    471447
153597    454912
153598    706589
153599    669816

[1024 rows x 1 columns]
_________
        C.COPYNO
153600    643113
153601    868671
153602    643110
153603    533665
153604    702901
...          ...
154619    409626
154620    473656
154621    356280
154622    233734
154623    342612

[1024 rows x 1 columns]
_________
        C.COPYNO
154624    673392
154625    198565
154626    184824
154627    160279
154628    160277
...          ...
155643    178942
155644    222159
155645    361776
155646    178939
155647    155091

[1024 rows x 1 columns]
_________
        C.COPYNO
155648    548332
155649    178937
155650    174689
155651    179301
155652    179300
...          ...
156667    596936
156668    606399
156669    661740
156670    414293
156671    660559

[1024 rows x 1 columns]
_________
        C.COPYNO
156672    106339
156673    106345
156674    811639
156675    811719
156676    811734
...          ...
157691    641927
157692    641926
157693    657785
157694    847781
157695    840548

[1024 rows x 1 columns]
_________
        C.COPYNO
157696    691307
157697    138537
157698    554689
157699    554686
157700    616988
...          ...
158715    180070
158716    180196
158717    219244
158718    180074
158719    179982

[1024 rows x 1 columns]
_________
       C.COPYNO
158720   179983
158721   270552
158722   179985
158723   179986
158724   179987
...         ...
159739   561104
159740   234929
159741   234934
159742   234864
159743   766255

[1024 rows x 1 columns]
_________
        C.COPYNO
159744    221750
159745    234865
159746    175126
159747    175127
159748     96927
...          ...
160763    730513
160764    712114
160765    778033
160766    836558
160767    731886

[1024 rows x 1 columns]
_________
        C.COPYNO
160768    712639
160769    712674
160770    731721
160771    777882
160772    832991
...          ...
161787    175776
161788    175372
161789    175647
161790    399498
161791    399607

[1024 rows x 1 columns]

_________
        C.COPYNO
161792    399930
161793    399922
161794    441867
161795    440660
161796    476056
...          ...
162811    565525
162812    826600
162813    178650
162814    360627
162815    368454

[1024 rows x 1 columns]
_________
        C.COPYNO
162816    840215
162817    846930
162818    893383
162819    629137
162820    773775
...          ...
163835    792730
163836    792732
163837    815134
163838    827145
163839    832421

[1024 rows x 1 columns]
_________
        C.COPYNO
163840    802738
163841    802739
163842    632706
163843    732118
163844    602492
...          ...
164859    891744
164860    895857
164861    895856
164862    774078
164863    774079

[1024 rows x 1 columns]
_________
        C.COPYNO
164864    738721
164865    909578
164866    909524
164867    909539
164868    909587
...          ...
165883    749410
165884    768113
165885    809592
165886    809583
165887    751787

[1024 rows x 1 columns]
_________
        C.COPYNO
165888    834609
165889    836197
165890    836196
165891    834731
165892    782386
...          ...
166907    652808
166908    640632
166909    617196
166910    647357
166911    647363

[1024 rows x 1 columns]
_________
        C.COPYNO
166912    643650
166913    696245
166914    696250
166915    690778
166916    695182
...          ...
167931    629707
167932    836701
167933    810266
167934    810850
167935    813621

[1024 rows x 1 columns]
_________
        C.COPYNO
167936    873540
167937    787949
167938    787862
167939    844279
167940    844280
...          ...
168955     18072
168956    597089
168957    597088
168958    646627
168959    920938

[1024 rows x 1 columns]
_________
        C.COPYNO
168960     18186
168961    358637
168962    363220
168963    428254
168964     18214
...          ...
169979    775079
169980    584418
169981    752274
169982    824359
169983    880524

[1024 rows x 1 columns]
_________
        C.COPYNO
169984    577298
169985    606640
169986    843969
169987     21935
169988     21940
...          ...
171003    501837
171004    525392
171005    524501
171006    527403
171007    526907

[1024 rows x 1 columns]
_________
        C.COPYNO
171008    546157
171009    546504
171010    560170
171011    560130
171012    560129
...          ...
172027    535414
172028    553650
172029    732383
172030    630175
172031    722256

[1024 rows x 1 columns]
_________
        C.COPYNO
172032    184697
172033    136793
172034    710634
172035    532918
172036    609763
...          ...
173051     10750
173052     10809
173053    646294
173054    571186
173055     10941

[1024 rows x 1 columns]
_________
        C.COPYNO
173056     10986
173057     52868
173058     52869
173059     10991
173060    365303
...          ...
174075    735106
174076    734691
174077    806765
174078    721990
174079    889751

[1024 rows x 1 columns]
_________
        C.COPYNO
174080    839588
174081    654674
174082    847357
174083    729345
174084    741088
...          ...
175099    710418
175100    538544
175101    641650
175102    905681
175103    816073

[1024 rows x 1 columns]
_________
        C.COPYNO
175104    729195
175105    475166
175106    563227
175107    579511
175108    881612
...          ...
176123    552931
176124    228785
176125    176255
176126    229143
176127    561124

[1024 rows x 1 columns]
_________
        C.COPYNO
176128    176269
176129    176275
176130    176278
176131    176282
176132    176283
...          ...
177147    763574
177148    765140
177149    510194
177150    667030
177151    725350

[1024 rows x 1 columns]
_________
        C.COPYNO
177152  649366.0
177153  770845.0
177154  532894.0
177155  807553.0
177156  642898.0
...          ...
178171  845089.0
178172  852215.0
178173  925460.0
178174  656030.0
178175  656031.0

[1024 rows x 1 columns]
_________
        C.COPYNO
178176    849025
178177    852995
178178    848423
178179    638241
178180     55102
...          ...
179195     29295
179196     29309
179197     29356
179198     29390
179199     29393

[1024 rows x 1 columns]
_________
        C.COPYNO
179200     29397
179201     29398
179202     29401
179203     29425
179204     25204
...          ...
180219    851638
180220    829297
180221    801649
180222    856989
180223    922457

[1024 rows x 1 columns]
_________
        C.COPYNO
180224    856987
180225    806265
180226    821076
180227    821078
180228    821079
...          ...
181243    846695
181244    847160
181245    644420
181246    621158
181247    611537

[1024 rows x 1 columns]
_________
        C.COPYNO
181248    611497
181249    792966
181250    790842
181251    656267
181252    656270
...          ...
182267    693954
182268    791765
182269    803309
182270    596856
182271    859620

[1024 rows x 1 columns]
_________
        C.COPYNO
182272    830538
182273    773172
182274    707860
182275    726497
182276    743546
...          ...
183291    627268
183292    841766
183293    876498
183294    607393
183295    636920

[1024 rows x 1 columns]
_________
        C.COPYNO
183296    851996
183297    873323
183298    767838
183299    524835
183300    531649
...          ...
184315    778627
184316    516153
184317    516153
184318    803598
184319    771411

[1024 rows x 1 columns]
_________
        C.COPYNO
184320    792728
184321    811555
184322    606779
184323    428820
184324    428819
...          ...
185339     46252
185340    634436
185341    818383
185342    682373
185343    183904

[1024 rows x 1 columns]
_________
        C.COPYNO
185344    641338
185345     46268
185346    755222
185347     46316
185348    345654
...          ...
186363    767336
186364     11044
186365     11079
186366     11087
186367    539658

[1024 rows x 1 columns]
_________
        C.COPYNO
186368    694664
186369    612714
186370    743558
186371     11100
186372     11101
...          ...
187387     31127
187388     31157
187389     31155
187390     31178
187391     31194

[1024 rows x 1 columns]
_________
        C.COPYNO
187392     33013
187393     33046
187394     33103
187395     33120
187396     33126
...          ...
188411    829447
188412    476142
188413    661522
188414    526001
188415    843561

[1024 rows x 1 columns]
_________
        C.COPYNO
188416    858441
188417    721467
188418    643960
188419    786672
188420    568219
...          ...
189435    536167
189436    747498
189437    587829
189438    791555
189439    791556

[1024 rows x 1 columns]
_________
        C.COPYNO
189440    799932
189441    807444
189442    861689
189443    861690
189444    610649
...          ...
190459    882666
190460    851915
190461    757420
190462    831933
190463    888347

[1024 rows x 1 columns]
_________
        C.COPYNO
190464    850118
190465    888339
190466    850391
190467    850290
190468    850213
...          ...
191483    506802
191484    513879
191485    513433
191486    350353
191487    365185

[1024 rows x 1 columns]
_________
        C.COPYNO
191488    473889
191489    469588
191490    164954
191491    164843
191492    164956
...          ...
192507    404813
192508    771508
192509    811033
192510    811034
192511     21757

[1024 rows x 1 columns]
_________
        C.COPYNO
192512    826599
192513    867277
192514     29279
192515    132538
192516    132539
...          ...
193531    598857
193532    598859
193533    598869
193534    598876
193535    598890

[1024 rows x 1 columns]
_________
        C.COPYNO
193536    598761
193537    496925
193538    598763
193539    496934
193540    598767
...          ...
194555    889019
194556    889020
194557    893891
194558    828888
194559    832891

[1024 rows x 1 columns]
_________
        C.COPYNO
194560    889012
194561    889014
194562    893893
194563    832858
194564    828839
...          ...
195579    657085
195580    694162
195581     44629
195582     44633
195583    917449

[1024 rows x 1 columns]
_________
        C.COPYNO
195584    665405
195585    664900
195586    332934
195587    813597
195588    198411
...          ...
196603    858984
196604    864045
196605    718101
196606    682368
196607    637425

[1024 rows x 1 columns]
_________
        C.COPYNO
196608    795481
196609    711293
196610    717854
196611    644142
196612    710712
...          ...
197627    529522
197628    542807
197629    533305
197630    533306
197631    533309

[1024 rows x 1 columns]
_________
        C.COPYNO
197632    533313
197633    533828
197634    533883
197635    542790
197636    541685
...          ...
198651    264680
198652    732304
198653    789498
198654    789499
198655    841116

[1024 rows x 1 columns]
_________
        C.COPYNO
198656    843813
198657      2633
198658    501634
198659    501635
198660    501463
...          ...
199675    506391
199676    506397
199677    506919
199678    506920
199679    506939

[1024 rows x 1 columns]
_________
        C.COPYNO
199680    506963
199681    506418
199682    506471
199683    498180
199684    498244
...          ...
200699    822555
200700    837621
200701    781920
200702    348728
200703    540552

[1024 rows x 1 columns]
_________
        C.COPYNO
200704    596575
200705    812331
200706    837628
200707    812332
200708    837629
...          ...
201723    492209
201724    492171
201725    492181
201726    702771
201727    570068

[1024 rows x 1 columns]
_________
        C.COPYNO
201728    182385
201729     29722
201730     29725
201731     29726
201732     29731
...          ...
202747    199580
202748    814519
202749    471518
202750    534527
202751    462757

[1024 rows x 1 columns]
_________
        C.COPYNO
202752    571499
202753    465170
202754    512432
202755    800536
202756    197240
...          ...
203771    705030
203772    702811
203773    702815
203774     26588
203775    717079

[1024 rows x 1 columns]
_________
        C.COPYNO
203776    780029
203777    745022
203778    485765
203779    491011
203780    485764
...          ...
204795    534810
204796    543272
204797    712865
204798    718855
204799    746957

[1024 rows x 1 columns]
_________
        C.COPYNO
204800    615430
204801    603012
204802    712936
204803    712937
204804     94988
...          ...
205819     81773
205820     81775
205821     81776
205822     81777
205823     81779

[1024 rows x 1 columns]
_________
        C.COPYNO
205824     81780
205825     81781
205826     81782
205827     81784
205828     81785
...          ...
206843    855017
206844     84746
206845     84763
206846    607014
206847     84776

[1024 rows x 1 columns]
_________
        C.COPYNO
206848     84767
206849     84772
206850    352571
206851    135594
206852    221229
...          ...
207867    890516
207868    890517
207869    891084
207870    891085
207871    891374

[1024 rows x 1 columns]
_________
        C.COPYNO
207872    902647
207873    904187
207874    580745
207875     51552
207876    820089
...          ...
208891    146563
208892    146564
208893    676428
208894    669443
208895    673598

[1024 rows x 1 columns]
_________
        C.COPYNO
208896    628256
208897    596052
208898    610495
208899    672458
208900    610371
...          ...
209915    165019
209916    165020
209917    165021
209918    165022
209919    165043

[1024 rows x 1 columns]
_________
        C.COPYNO
209920    165042
209921    165044
209922    165045
209923    165046
209924    165040
...          ...
210939    593275
210940    606143
210941    619975
210942    619580
210943    714489

[1024 rows x 1 columns]
_________
        C.COPYNO
210944    714506
210945    714581
210946    559449
210947    553179
210948    831108
...          ...
211963    147711
211964    147712
211965    147714
211966    147716
211967    147717

[1024 rows x 1 columns]
_________
        C.COPYNO
211968    147718
211969    147719
211970    147721
211971    147723
211972    147724
...          ...
212987    732359
212988    637007
212989    714904
212990    893724
212991    642687

[1024 rows x 1 columns]
_________
        C.COPYNO
212992    805915
212993    805198
212994    782761
212995    763471
212996    675153
...          ...
214011    477762
214012    788961
214013    788962
214014    465021
214015    470741

[1024 rows x 1 columns]
_________
        C.COPYNO
214016    384991
214017    630978
214018    654418
214019    901014
214020    752350
...          ...
215035    149015
215036    149016
215037    149017
215038    149018
215039    149019

[1024 rows x 1 columns]
_________
        C.COPYNO
215040    149020
215041    149022
215042    197736
215043    188398
215044    149023
...          ...
216059    801664
216060    713672
216061    729541
216062    729538
216063    647312

[1024 rows x 1 columns]

_________
        C.COPYNO
216064    793003
216065    810039
216066    793004
216067    793005
216068    793745
...          ...
217083    900487
217084    646898
217085    464636
217086    464633
217087    149716

[1024 rows x 1 columns]
_________
        C.COPYNO
217088    149717
217089    149718
217090    149719
217091    149720
217092    465701
...          ...
218107    750164
218108    750187
218109    150038
218110    185413
218111    217993

[1024 rows x 1 columns]
_________
        C.COPYNO
218112    385204
218113    385393
218114    750174
218115    735613
218116    686632
...          ...
219131    807089
219132    807090
219133    807091
219134    807093
219135    807094

[1024 rows x 1 columns]
_________
        C.COPYNO
219136    807092
219137    807095
219138    850900
219139    732076
219140    150349
...          ...
220155    204998
220156    204999
220157    454738
220158    472758
220159    480013

[1024 rows x 1 columns]
_________
        C.COPYNO
220160    487883
220161    488428
220162    525560
220163    525575
220164    525581
...          ...
221179    149536
221180    149553
221181    149567
221182    149578
221183    149615

[1024 rows x 1 columns]
_________
        C.COPYNO
221184    149616
221185    149617
221186    149618
221187    442077
221188    570422
...          ...
222203    548825
222204    151293
222205    151294
222206    151295
222207    151296

[1024 rows x 1 columns]
_________
        C.COPYNO
222208    151298
222209    151297
222210    151299
222211    151042
222212    151244
...          ...
223227    152144
223228    461144
223229    152233
223230    152235
223231    152236

[1024 rows x 1 columns]
_________
        C.COPYNO
223232    152237
223233    152238
223234    152239
223235    152240
223236    152241
...          ...
224251    680620
224252    680621
224253    680622
224254    650140
224255    860995

[1024 rows x 1 columns]
_________
        C.COPYNO
224256    860996
224257    744647
224258    744648
224259    704849
224260    699995
...          ...
225275    152365
225276    152366
225277    152371
225278    152368
225279    152147

[1024 rows x 1 columns]
_________
        C.COPYNO
225280    152174
225281    152184
225282    152175
225283    152178
225284    152203
...          ...
226299    742890
226300    604861
226301    610295
226302    152733
226303    152734

[1024 rows x 1 columns]
_________
        C.COPYNO
226304    379452
226305    669693
226306    152737
226307    152738
226308    152739
...          ...
227323    152899
227324    152900
227325    152901
227326    769878
227327    633832

[1024 rows x 1 columns]
_________
       C.COPYNO
227328   706897
227329   608315
227330   769874
227331   185636
227332   185637
...         ...
228347   153180
228348   153182
228349   153184
228350   153185
228351   153186

[1024 rows x 1 columns]
_________
        C.COPYNO
228352    153187
228353    409498
228354    153162
228355    153164
228356    153165
...          ...
229371    844921
229372    871380
229373    154158
229374    154159
229375    154163

[1024 rows x 1 columns]
_________
        C.COPYNO
229376    154164
229377    154165
229378    566596
229379    154166
229380    198538
...          ...
230395    625500
230396    153750
230397    153751
230398    218044
230399    153752

[1024 rows x 1 columns]
_________
       C.COPYNO
230400   807431
230401   579444
230402   627541
230403   643748
230404   611489
...         ...
231419   695900
231420   155402
231421   339562
231422   825442
231423   155403

[1024 rows x 1 columns]
_________
        C.COPYNO
231424    155143
231425    155405
231426    797659
231427    155409
231428    155410
...          ...
232443     95432
232444      1829
232445      1830
232446      1831
232447      1834

[1024 rows x 1 columns]
_________
        C.COPYNO
232448      1835
232449      1837
232450      1839
232451      1840
232452     95443
...          ...
233467    156373
233468    156374
233469    156377
233470    156376
233471    156379

[1024 rows x 1 columns]
_________
        C.COPYNO
233472    156382
233473    156383
233474    156384
233475    156390
233476    156391
...          ...
234491    157030
234492    173172
234493    157031
234494    157035
234495    157036

[1024 rows x 1 columns]
_________
       C.COPYNO
234496   157045
234497   157026
234498   157043
234499   157048
234500   157049
...         ...
235515   157362
235516   157356
235517   157357
235518   157358
235519   157359

[1024 rows x 1 columns]
_________
        C.COPYNO
235520    157360
235521    157361
235522    157353
235523    157366
235524    157153
...          ...
236539    752919
236540    475329
236541    524248
236542    523445
236543    524058

[1024 rows x 1 columns]
_________
        C.COPYNO
236544    579386
236545    602372
236546    593359
236547    593394
236548    593710
...          ...
237563    217911
237564    217914
237565    619916
237566    217916
237567    157715

[1024 rows x 1 columns]
_________
        C.COPYNO
237568    157717
237569    651588
237570    681224
237571    157738
237572    157739
...          ...
238587    766051
238588    785259
238589    785086
238590    399579
238591    434739

[1024 rows x 1 columns]
_________
        C.COPYNO
238592    579422
238593    593353
238594    593716
238595    159218
238596    159208
...          ...
239611    686908
239612    663421
239613    662512
239614    663703
239615    743035

[1024 rows x 1 columns]
_________
        C.COPYNO
239616    465291
239617    453826
239618    524579
239619    586439
239620    586926
...          ...
240635    160281
240636    160282
240637    160283
240638    160284
240639    160309

[1024 rows x 1 columns]
_________
        C.COPYNO
240640    581214
240641    160318
240642    352642
240643    352638
240644    160329
...          ...
241659    631223
241660    645363
241661    648144
241662    648143
241663    828409

[1024 rows x 1 columns]
_________
        C.COPYNO
241664    160561
241665    787230
241666    160564
241667    160565
241668    843959
...          ...
242683    887718
242684    873037
242685    857745
242686    617930
242687    721280

[1024 rows x 1 columns]
_________
        C.COPYNO
242688    694714
242689    821850
242690    906994
242691    906999
242692    507548
...          ...
243707    154348
243708    563459
243709    174407
243710    521674
243711    169489

[1024 rows x 1 columns]
_________
        C.COPYNO
243712    161232
243713    200185
243714    161233
243715    174392
243716    217336
...          ...
244731    162199
244732    162210
244733    162210
244734    162211
244735    162211

[1024 rows x 1 columns]
_________
        C.COPYNO
244736    162200
244737    162200
244738    162201
244739    162201
244740    162202
...          ...
245755    623106
245756    726332
245757    623109
245758    623108
245759    623105

[1024 rows x 1 columns]
_________
        C.COPYNO
245760    857496
245761    727995
245762    764866
245763    764813
245764    778658
...          ...
246779    162295
246780    162296
246781    162297
246782    162298
246783    162299

[1024 rows x 1 columns]
_________
        C.COPYNO
246784    162300
246785    162304
246786    162307
246787    162318
246788    162332
...          ...
247803    185209
247804    163138
247805    163140
247806    163142
247807    463896

[1024 rows x 1 columns]
_________
        C.COPYNO
247808    163144
247809    163145
247810    163117
247811    163116
247812    163119
...          ...
248827    728615
248828    681471
248829    760880
248830    645375
248831    645373

[1024 rows x 1 columns]
_________
        C.COPYNO
248832    624621
248833     14163
248834    664203
248835    731601
248836    685626
...          ...
249851    163308
249852    163136
249853    196671
249854    196672
249855    196674

[1024 rows x 1 columns]
_________
        C.COPYNO
249856    196676
249857    158670
249858     64702
249859    163313
249860    163318
...          ...
250875    169518
250876    170529
250877    170532
250878    170530
250879    158765

[1024 rows x 1 columns]
_________
        C.COPYNO
250880    158768
250881    177337
250882    158774
250883    163538
250884    163410
...          ...
251899    217064
251900    217065
251901    491849
251902    659566
251903    832363

[1024 rows x 1 columns]
_________
        C.COPYNO
251904    159129
251905    159131
251906    572036
251907    813801
251908    159130
...          ...
252923    164265
252924    696324
252925    164347
252926    164348
252927    563339

[1024 rows x 1 columns]
_________
        C.COPYNO
252928    164349
252929    545922
252930    191654
252931    191656
252932    191655
...          ...
253947    661805
253948    434616
253949    434745
253950    435651
253951    435660

[1024 rows x 1 columns]
_________
        C.COPYNO
253952    434747
253953    435652
253954    441831
253955    453665
253956    681551
...          ...
254971    771154
254972    661156
254973    724029
254974    751616
254975    734129

[1024 rows x 1 columns]
_________
        C.COPYNO
254976    510617
254977    602287
254978    602694
254979    864023
254980    651686
...          ...
255995    149629
255996    149630
255997    149489
255998    149490
255999    144221

[1024 rows x 1 columns]
_________
       C.COPYNO
256000   268881
256001   154251
256002   154254
256003   154259
256004   154247
...         ...
257019   177647
257020   177646
257021   177645
257022   177643
257023   177642

[1024 rows x 1 columns]
_________
        C.COPYNO
257024    177641
257025    177640
257026    177638
257027    177637
257028    178048
...          ...
258043    409215
258044    409233
258045    409212
258046    409293
258047    409205

[1024 rows x 1 columns]
_________
        C.COPYNO
258048    409246
258049    409273
258050    421618
258051    421619
258052    421908
...          ...
259067    643354
259068    165865
259069    829973
259070    707933
259071    889352

[1024 rows x 1 columns]
_________
        C.COPYNO
259072    682429
259073    711085
259074    647949
259075    603485
259076    513899
...          ...
260091    520917
260092    520923
260093    520923
260094    520920
260095    520920

[1024 rows x 1 columns]
_________
        C.COPYNO
260096    520916
260097    520916
260098    520922
260099    520922
260100    520915
...          ...
261115    514271
261116    396687
261117    166729
261118    166731
261119    166732

[1024 rows x 1 columns]
_________
        C.COPYNO
261120    166733
261121    166734
261122    166736
261123    166745
261124    420587
...          ...
262139    657741
262140    657745
262141    657745
262142    404288
262143    404289

[1024 rows x 1 columns]
_________
        C.COPYNO
262144    404290
262145    397743
262146    397917
262147    397742
262148    526383
...          ...
263163    757068
263164    751983
263165    395438
263166    789415
263167    865163

[1024 rows x 1 columns]
_________
        C.COPYNO
263168    796057
263169    796057
263170    634845
263171    595764
263172    647891
...          ...
264187    583981
264188    678542
264189    872866
264190    648682
264191    690154

[1024 rows x 1 columns]
_________
        C.COPYNO
264192    579402
264193    654713
264194    678725
264195    678724
264196    579504
...          ...
265211    520894
265212    520893
265213    520889
265214    520890
265215    525387

[1024 rows x 1 columns]
_________
       C.COPYNO
265216   524850
265217   714504
265218   714505
265219   714522
265220   809813
...         ...
266235   185573
266236   185567
266237   185620
266238   185563
266239   185581

[1024 rows x 1 columns]
_________
        C.COPYNO
266240    185582
266241    185583
266242    185559
266243    185609
266244    185611
...          ...
267259     64133
267260     64139
267261     64140
267262    377751
267263    377753

[1024 rows x 1 columns]

_________
        C.COPYNO
267264    377754
267265    699652
267266    884204
267267    884209
267268     64173
...          ...
268283    493204
268284    490365
268285    690974
268286    587840
268287    671051

[1024 rows x 1 columns]
_________
        C.COPYNO
268288    652610
268289    651022
268290    660745
268291    654525
268292    696336
...          ...
269307    347954
269308    483887
269309    729334
269310    729334
269311    525054

[1024 rows x 1 columns]
_________
        C.COPYNO
269312    525054
269313    857902
269314    857902
269315    857903
269316    857903
...          ...
270331    597955
270332    817419
270333    180078
270334    173646
270335    385117

[1024 rows x 1 columns]
_________
        C.COPYNO
270336    585564
270337    156069
270338    189088
270339    184249
270340     85692
...          ...
271355     69100
271356     69111
271357     69122
271358     69102
271359     69157

[1024 rows x 1 columns]
_________
        C.COPYNO
271360     69158
271361     69106
271362     69178
271363     69191
271364    577171
...          ...
272379    138788
272380    808932
272381    138789
272382      2549
272383    138790

[1024 rows x 1 columns]
_________
        C.COPYNO
272384    138791
272385    138792
272386    138794
272387    138795
272388    809586
...          ...
273403      2101
273404      2102
273405      2136
273406     76505
273407     77686

[1024 rows x 1 columns]
_________
        C.COPYNO
273408     77741
273409      2156
273410      2170
273411     86010
273412    689655
...          ...
274427    664702
274428    664702
274429    664706
274430    664706
274431    664709

[1024 rows x 1 columns]
_________
        C.COPYNO
274432    664709
274433    658342
274434    699589
274435    704304
274436    759676
...          ...
275451    803924
275452    720162
275453    735779
275454    735805
275455    774559

[1024 rows x 1 columns]
_________
        C.COPYNO
275456    778857
275457    756312
275458    778858
275459    778859
275460    785370
...          ...
276475      8908
276476      8910
276477      8914
276478      8614
276479      8600

[1024 rows x 1 columns]
_________
        C.COPYNO
276480      8090
276481      9062
276482      9066
276483      9067
276484      9076
...          ...
277499    700835
277500    720263
277501    700837
277502    574992
277503    700836

[1024 rows x 1 columns]
_________
        C.COPYNO
277504    678754
277505    678759
277506    678758
277507    678757
277508    678756
...          ...
278523    771894
278524    699376
278525    699382
278526    699383
278527    699375

[1024 rows x 1 columns]
_________
        C.COPYNO
278528    699381
278529    771895
278530    771946
278531    771948
278532    772005
...          ...
279547    802718
279548    861740
279549    887811
279550    718599
279551    736696

[1024 rows x 1 columns]
_________
        C.COPYNO
279552    798642
279553    727735
279554    637825
279555    589673
279556    792862
...          ...
280571      5651
280572     77079
280573    351771
280574    618102
280575    474963

[1024 rows x 1 columns]
_________
        C.COPYNO
280576     77116
280577    693201
280578    703822
280579    639760
280580    728218
...          ...
281595    780042
281596    780043
281597      5601
281598      5642
281599     80962

[1024 rows x 1 columns]
_________
        C.COPYNO
281600      5666
281601    475081
281602      5746
281603      5750
281604      5752
...          ...
282619      5785
282620    730878
282621    134864
282622    736283
282623    651454

[1024 rows x 1 columns]
_________
        C.COPYNO
282624    651455
282625    658607
282626    658603
282627    657615
282628    896756
...          ...
283643    636623
283644      8733
283645     85464
283646    801874
283647    654782

[1024 rows x 1 columns]
_________
        C.COPYNO
283648      8751
283649      8775
283650    669442
283651    633995
283652    681596
...          ...
284667    651180
284668    535625
284669    587826
284670    661518
284671    661519

[1024 rows x 1 columns]
_________
        C.COPYNO
284672    722801
284673    687445
284674    688302
284675    721279
284676    704146
...          ...
285691      9050
285692    647430
285693    621439
285694      9119
285695      9176

[1024 rows x 1 columns]
_________
        C.COPYNO
285696     72247
285697    721962
285698    504466
285699    758342
285700    752769
...          ...
286715    758229
286716    745648
286717    745649
286718    733235
286719    748408

[1024 rows x 1 columns]
_________
        C.COPYNO
286720    745510
286721    744605
286722    744606
286723    749400
286724    911394
...          ...
287739    740837
287740    751275
287741    851692
287742    887799
287743    464776

[1024 rows x 1 columns]
_________
        C.COPYNO
287744    460869
287745    843563
287746    770177
287747    886338
287748    755264
...          ...
288763    623654
288764    743103
288765    808109
288766    647987
288767    184108

[1024 rows x 1 columns]
_________
        C.COPYNO
288768     85418
288769     85422
288770     85424
288771     15269
288772    720641
...          ...
289787    798201
289788     11445
289789    821917
289790    755234
289791    904008

[1024 rows x 1 columns]
_________
        C.COPYNO
289792    866445
289793    658329
289794     11407
289795     85381
289796    898701
...          ...
290811    619453
290812    627354
290813    750625
290814    696326
290815    713659

[1024 rows x 1 columns]
_________
        C.COPYNO
290816    685330
290817    904213
290818    905984
290819    863892
290820    770119
...          ...
291835    496123
291836    482402
291837    513809
291838    525840
291839    525819

[1024 rows x 1 columns]
_________
        C.COPYNO
291840    525845
291841    525788
291842    559834
291843    559835
291844    559850
...          ...
292859    659819
292860    602570
292861    740789
292862    585928
292863    562778

[1024 rows x 1 columns]
_________
        C.COPYNO
292864     12300
292865     12315
292866    644878
292867    646929
292868     12339
...          ...
293883    470176
293884    522515
293885    640633
293886    533700
293887    787609

[1024 rows x 1 columns]
_________
        C.COPYNO
293888     15858
293889    893169
293890    706899
293891    871584
293892     81679
...          ...
294907    881151
294908    170126
294909    154843
294910    342345
294911    342348

[1024 rows x 1 columns]
_________
        C.COPYNO
294912    342351
294913    519407
294914    519406
294915    180561
294916    515657
...          ...
295931     15120
295932     57868
295933    621715
295934    805709
295935    638593

[1024 rows x 1 columns]
_________
        C.COPYNO
295936    881065
295937    659430
295938    736840
295939    532653
295940    863368
...          ...
296955     16364
296956     16368
296957     16370
296958     16460
296959     16469

[1024 rows x 1 columns]
_________
        C.COPYNO
296960     68915
296961     68920
296962     68924
296963    883477
296964     96508
...          ...
297979    878082
297980    696040
297981     15271
297982    782800
297983    792520

[1024 rows x 1 columns]
_________
        C.COPYNO
297984     80017
297985    876875
297986    678843
297987    756643
297988    756644
...          ...
299003     15734
299004     15736
299005     15759
299006    883563
299007    883564

[1024 rows x 1 columns]
_________
        C.COPYNO
299008    883565
299009    890159
299010     15801
299011    542454
299012     15850
...          ...
300027    803486
300028    807428
300029    821671
300030    821667
300031    847979

[1024 rows x 1 columns]
_________
        C.COPYNO
300032    854059
300033    860488
300034     12294
300035     98370
300036    340335
...          ...
301051    170230
301052    169924
301053    169925
301054    170315
301055    170314

[1024 rows x 1 columns]
_________
        C.COPYNO
301056    170042
301057    170043
301058    170220
301059    170221
301060    170251
...          ...
302075    890997
302076    703659
302077    605762
302078     15976
302079     19534

[1024 rows x 1 columns]
_________
        C.COPYNO
302080     19559
302081     19603
302082     19641
302083     19688
302084     19691
...          ...
303099     16499
303100     16500
303101     16503
303102    652826
303103    473350

[1024 rows x 1 columns]
_________
        C.COPYNO
303104    473818
303105    483472
303106    482864
303107    489059
303108    505757
...          ...
304123    886653
304124    558925
304125    857693
304126    632053
304127    811130

[1024 rows x 1 columns]
_________
        C.COPYNO
304128    836421
304129    771847
304130    824039
304131    783127
304132    766293
...          ...
305147    638122
305148    859978
305149    684085
305150    797689
305151    816433

[1024 rows x 1 columns]
_________
        C.COPYNO
305152    891379
305153    895107
305154    800071
305155    684571
305156    752584
...          ...
306171    536810
306172    380802
306173    465946
306174    471435
306175    489845

[1024 rows x 1 columns]
_________
        C.COPYNO
306176    906375
306177    462647
306178    483666
306179    564283
306180    526072
...          ...
307195     23515
307196     23520
307197     23521
307198     23523
307199     23524

[1024 rows x 1 columns]
_________
        C.COPYNO
307200     23529
307201     23533
307202     23543
307203     23551
307204     23436
...          ...
308219    629851
308220    564634
308221    541151
308222     19785
308223     19786

[1024 rows x 1 columns]
_________
        C.COPYNO
308224    540613
308225    441025
308226    793008
308227    793097
308228    787428
...          ...
309243    172509
309244    485594
309245    867790
309246    488412
309247    332591

[1024 rows x 1 columns]
_________
        C.COPYNO
309248    347332
309249    547069
309250    600387
309251    138453
309252    196598
...          ...
310267    503845
310268    503842
310269    503847
310270    508052
310271    508065

[1024 rows x 1 columns]
_________
        C.COPYNO
310272    508064
310273    508063
310274    508058
310275    510422
310276    510423
...          ...
311291    861189
311292    867503
311293    837751
311294    840213
311295    844046

[1024 rows x 1 columns]
_________
        C.COPYNO
311296    820841
311297    837436
311298    793586
311299    814408
311300    859154
...          ...
312315    859738
312316    577821
312317    642442
312318    642440
312319    642438

[1024 rows x 1 columns]
_________
       C.COPYNO
312320   912858
312321   793029
312322   793736
312323   805573
312324   805730
...         ...
313339   809286
313340   809287
313341   809340
313342   809920
313343   809968

[1024 rows x 1 columns]
_________
        C.COPYNO
313344    809996
313345    810026
313346    810084
313347    669498
313348    483250
...          ...
314363    833549
314364     20574
314365     20582
314366     20532
314367     20555

[1024 rows x 1 columns]
_________
        C.COPYNO
314368     20232
314369     23045
314370     23418
314371     20646
314372     20766
...          ...
315387     20696
315388     20694
315389     20692
315390    397492
315391    696052

[1024 rows x 1 columns]
_________
        C.COPYNO
315392    365561
315393    815256
315394     20719
315395    729575
315396    800739
...          ...
316411    912503
316412    864151
316413    908119
316414    790962
316415    791838

[1024 rows x 1 columns]
_________
        C.COPYNO
316416    754581
316417     84250
316418    364742
316419     18955
316420     18923
...          ...
317435    724137
317436    724139
317437    724138
317438    677310
317439    677032

[1024 rows x 1 columns]
_________
        C.COPYNO
317440    677308
317441    677300
317442    677029
317443    677297
317444    724066
...          ...
318459     23609
318460     24787
318461     23623
318462    462534
318463    605362

[1024 rows x 1 columns]
_________
        C.COPYNO
318464    855212
318465    855215
318466    543244
318467    693131
318468    693132
...          ...
319483     23315
319484     23370
319485     23371
319486     23397
319487     23479

[1024 rows x 1 columns]
_________
        C.COPYNO
319488     23596
319489     23347
319490     23348
319491     23679
319492     23680
...          ...
320507    866066
320508    866067
320509    571577
320510    684105
320511    730863

[1024 rows x 1 columns]
_________
        C.COPYNO
320512    774262
320513    677921
320514    886476
320515    667118
320516    761641
...          ...
321531    665043
321532    737164
321533    737172
321534    743007
321535    669339

[1024 rows x 1 columns]
_________
        C.COPYNO
321536    820967
321537    844202
321538    865228
321539    820968
321540    820969
...          ...
322555    855532
322556    855533
322557    860455
322558    556779
322559    564181

[1024 rows x 1 columns]

_________
        C.COPYNO
322560    820180
322561    777469
322562    733038
322563    743717
322564    726604
...          ...
323579    564146
323580    564147
323581    845731
323582    564150
323583    564151

[1024 rows x 1 columns]
_________
        C.COPYNO
323584    845730
323585    564153
323586    564155
323587    845729
323588    564158
...          ...
324603     24587
324604    769604
324605    774188
324606    763650
324607    763649

[1024 rows x 1 columns]
_________
        C.COPYNO
324608    795620
324609    658359
324610    837681
324611    720069
324612    731473
...          ...
325627     84336
325628     84339
325629     84341
325630     84344
325631    132242

[1024 rows x 1 columns]
_________
        C.COPYNO
325632     23792
325633     23802
325634     84396
325635     24714
325636     23855
...          ...
326651    839567
326652    855350
326653    831373
326654    855589
326655    890599

[1024 rows x 1 columns]
_________
        C.COPYNO
326656    896791
326657    858841
326658    859251
326659    857628
326660    861628
...          ...
327675     84542
327676     84582
327677     23935
327678     23963
327679     23967

[1024 rows x 1 columns]
_________
        C.COPYNO
327680     23970
327681     84630
327682     84635
327683     84595
327684     84655
...          ...
328699    837823
328700    677998
328701     20255
328702     20252
328703     20248

[1024 rows x 1 columns]
_________
        C.COPYNO
328704     20262
328705     20261
328706    485321
328707     20273
328708    463012
...          ...
329723    738535
329724    791815
329725    838303
329726    873474
329727    657725

[1024 rows x 1 columns]
_________
        C.COPYNO
329728    657727
329729    800581
329730    811539
329731    692027
329732    674997
...          ...
330747    772069
330748    700606
330749    700602
330750    700601
330751    700604

[1024 rows x 1 columns]
_________
        C.COPYNO
330752    700603
330753    700607
330754    688291
330755    700608
330756    599135
...          ...
331771    664609
331772    850010
331773    817075
331774    820522
331775    672194

[1024 rows x 1 columns]
_________
        C.COPYNO
331776    866610
331777    638927
331778    825543
331779    825533
331780    750112
...          ...
332795    696235
332796    696236
332797    696237
332798    696238
332799    696239

[1024 rows x 1 columns]
_________
        C.COPYNO
332800    678179
332801    696240
332802    696241
332803    696242
332804    696243
...          ...
333819    401817
333820    401816
333821    563865
333822    649437
333823    544179

[1024 rows x 1 columns]
_________
        C.COPYNO
333824    776678
333825    583884
333826    699547
333827    744161
333828    718942
...          ...
334843     31357
334844    780372
334845    523209
334846    712933
334847    712935

[1024 rows x 1 columns]
_________
        C.COPYNO
334848    713589
334849     72364
334850     29013
334851     28898
334852    662298
...          ...
335867    883109
335868     24496
335869     24509
335870     24514
335871    584888

[1024 rows x 1 columns]
_________
        C.COPYNO
335872    423414
335873    582078
335874    796413
335875     81725
335876    136288
...          ...
336891    631791
336892    497782
336893    496226
336894    477000
336895     32122

[1024 rows x 1 columns]
_________
        C.COPYNO
336896    623881
336897     32139
336898     32179
336899    490429
336900    860789
...          ...
337915     27633
337916    221698
337917     27545
337918     27560
337919     81833

[1024 rows x 1 columns]
_________
        C.COPYNO
337920     81852
337921    901232
337922    465390
337923    453763
337924     81872
...          ...
338939    764602
338940     28153
338941    589650
338942     28079
338943     28104

[1024 rows x 1 columns]
_________
        C.COPYNO
338944     28134
338945     79920
338946     79922
338947     79924
338948    683583
...          ...
339963     32437
339964     28103
339965     28105
339966    824157
339967    200605

[1024 rows x 1 columns]
_________
        C.COPYNO
339968    728179
339969    732766
339970    803319
339971     28135
339972     86872
...          ...
340987    672538
340988    881537
340989     28149
340990    747565
340991    910075

[1024 rows x 1 columns]
_________
        C.COPYNO
340992    694393
340993    625928
340994    625929
340995    805052
340996     28165
...          ...
342011    339798
342012    343009
342013    607222
342014    585780
342015    590838

[1024 rows x 1 columns]
_________
        C.COPYNO
342016    630266
342017    802814
342018     86146
342019     86162
342020    681523
...          ...
343035    740378
343036    333885
343037     32241
343038     32153
343039     32131

[1024 rows x 1 columns]
_________
        C.COPYNO
343040    755178
343041    758410
343042    638272
343043    596990
343044    604605
...          ...
344059    198519
344060    537288
344061    420763
344062    347135
344063    423069

[1024 rows x 1 columns]
_________
        C.COPYNO
344064    678711
344065    783737
344066    583521
344067    136465
344068    537082
...          ...
345083    270508
345084    694319
345085    268973
345086     35620
345087     35621

[1024 rows x 1 columns]
_________
        C.COPYNO
345088    344049
345089    817647
345090    676490
345091    761416
345092    740149
...          ...
346107    893972
346108    648914
346109    781726
346110    679350
346111    172287

[1024 rows x 1 columns]
_________
        C.COPYNO
346112    779829
346113    618252
346114    693120
346115    636655
346116    599792
...          ...
347131    853423
347132    627777
347133    766402
347134    887655
347135    137375

[1024 rows x 1 columns]
_________
        C.COPYNO
347136     39611
347137    883776
347138     61248
347139     61250
347140    561298
...          ...
348155     33669
348156     33684
348157     33686
348158    828788
348159     33646

[1024 rows x 1 columns]
_________
        C.COPYNO
348160    834434
348161    798736
348162    830030
348163    830031
348164    859522
...          ...
349179     82810
349180    667337
349181    467066
349182     31790
349183     31804

[1024 rows x 1 columns]
_________
        C.COPYNO
349184     31808
349185     31810
349186     31812
349187     82844
349188     82848
...          ...
350203     32090
350204     32110
350205     32132
350206    772728
350207    772729

[1024 rows x 1 columns]
_________
        C.COPYNO
350208    772730
350209    416952
350210     32154
350211    618295
350212    772726
...          ...
351227    858684
351228    779859
351229    817650
351230    678289
351231     35732

[1024 rows x 1 columns]
_________
        C.COPYNO
351232     35750
351233     35770
351234     68586
351235     38910
351236    737572
...          ...
352251    779848
352252    826353
352253    826354
352254    870432
352255    740839

[1024 rows x 1 columns]
_________
        C.COPYNO
352256    883076
352257    883077
352258    788192
352259    695217
352260    744953
...          ...
353275    878118
353276    866997
353277    810392
353278    695514
353279    834441

[1024 rows x 1 columns]
_________
        C.COPYNO
353280    652969
353281    829193
353282    668216
353283     35830
353284    869386
...          ...
354299    714135
354300    714140
354301    568203
354302    449018
354303    346704

[1024 rows x 1 columns]
_________
        C.COPYNO
354304    404212
354305    821922
354306    727789
354307    614129
354308     70979
...          ...
355323    616172
355324    628051
355325    369887
355326    359556
355327    359593

[1024 rows x 1 columns]
_________
        C.COPYNO
355328    630786
355329    630891
355330    622167
355331    628048
355332    630798
...          ...
356347    672462
356348    924977
356349    672507
356350    925020
356351    672514

[1024 rows x 1 columns]
_________
        C.COPYNO
356352    925023
356353    662642
356354    545291
356355    899675
356356    759423
...          ...
357371     76547
357372     76548
357373    827738
357374    783749
357375     36129

[1024 rows x 1 columns]
_________
        C.COPYNO
357376    368335
357377     36100
357378    368334
357379     36119
357380    693395
...          ...
358395    589823
358396    626697
358397    571449
358398    589262
358399    621109

[1024 rows x 1 columns]
_________
        C.COPYNO
358400    621111
358401    621113
358402    589821
358403    916276
358404    757871
...          ...
359419    860262
359420    865308
359421    908967
359422    621103
359423    859982

[1024 rows x 1 columns]
_________
        C.COPYNO
359424    892143
359425    892142
359426    865329
359427    892296
359428    916449
...          ...
360443    623948
360444    661497
360445    661486
360446    660710
360447    674441

[1024 rows x 1 columns]
_________
        C.COPYNO
360448    576508
360449    557068
360450    582405
360451    577007
360452    619090
...          ...
361467    594376
361468    594375
361469    612086
361470    633474
361471    707061

[1024 rows x 1 columns]
_________
        C.COPYNO
361472    779016
361473    630321
361474    831693
361475    777956
361476    630377
...          ...
362491    759975
362492    838356
362493    838357
362494    831793
362495    831845

[1024 rows x 1 columns]
_________
        C.COPYNO
362496    594450
362497    545295
362498    771009
362499    835666
362500    831684
...          ...
363515    778932
363516    778956
363517    778957
363518    778961
363519    778962

[1024 rows x 1 columns]
_________
        C.COPYNO
363520    778963
363521    778967
363522    666585
363523    602272
363524    534289
...          ...
364539    751450
364540    751383
364541    751382
364542    751343
364543    751391

[1024 rows x 1 columns]
_________
        C.COPYNO
364544    751346
364545    751363
364546    751445
364547    751340
364548    751345
...          ...
365563    646247
365564    739973
365565    837930
365566    570718
365567    760039

[1024 rows x 1 columns]
_________
        C.COPYNO
365568    743846
365569    724744
365570    559038
365571    759758
365572    759759
...          ...
366587    909820
366588    760616
366589    920456
366590    759751
366591    594255

[1024 rows x 1 columns]
_________
        C.COPYNO
366592    759268
366593    794980
366594    751082
366595    919890
366596    891734
...          ...
367611     78889
367612    405373
367613    424264
367614    424262
367615    424032

[1024 rows x 1 columns]
_________
        C.COPYNO
367616    424039
367617    424038
367618    424037
367619    424036
367620    487259
...          ...
368635    721854
368636    721855
368637    752621
368638    753835
368639    909847

[1024 rows x 1 columns]
_________
        C.COPYNO
368640    721922
368641    717944
368642    895356
368643    342250
368644    709570
...          ...
369659    893582
369660     65176
369661     35548
369662    594963
369663    641554

[1024 rows x 1 columns]
_________
        C.COPYNO
369664    775992
369665     35522
369666    571690
369667    178131
369668    614247
...          ...
370683    887640
370684     40300
370685    306750
370686    858559
370687    829978

[1024 rows x 1 columns]
_________
        C.COPYNO
370688    888708
370689    666353
370690    647798
370691    647801
370692    750355
...          ...
371707     39539
371708     39565
371709     36614
371710     39594
371711     39617

[1024 rows x 1 columns]
_________
        C.COPYNO
371712     39661
371713     39666
371714    335274
371715     39715
371716     39718
...          ...
372731    179649
372732    193243
372733    193244
372734    193245
372735    842135

[1024 rows x 1 columns]
_________
        C.COPYNO
372736    890562
372737    882725
372738    430575
372739    332529
372740    430447
...          ...
373755    193453
373756    370282
373757    473119
373758    193454
373759    193455

[1024 rows x 1 columns]
_________
        C.COPYNO
373760    193456
373761    174127
373762    172291
373763    437193
373764    586145
...          ...
374779    615546
374780    779849
374781    812629
374782    834842
374783    763909

[1024 rows x 1 columns]
_________
        C.COPYNO
374784    806021
374785    806020
374786    615614
374787    853654
374788    869403
...          ...
375803    193565
375804    826888
375805    634473
375806    638300
375807    792228

[1024 rows x 1 columns]
_________
        C.COPYNO
375808    817837
375809    674287
375810    665716
375811    665423
375812    732189
...          ...
376827    664880
376828    664882
376829    678516
376830    664928
376831    423711

[1024 rows x 1 columns]
_________
        C.COPYNO
376832    666307
376833    664825
376834    664883
376835    575579
376836    615436
...          ...
377851    918283
377852    918285
377853    918348
377854    918349
377855    918361

[1024 rows x 1 columns]
_________
        C.COPYNO
377856    918364
377857    918366
377858    918467
377859    918469
377860    918470
...          ...
378875    375843
378876    375836
378877    639535
378878    639142
378879    638882

[1024 rows x 1 columns]
_________
        C.COPYNO
378880    195391
378881    195389
378882    182119
378883    639205
378884    179349
...          ...
379899    839352
379900    831228
379901    885842
379902    839343
379903    831238

[1024 rows x 1 columns]

_________
        C.COPYNO
379904    639045
379905    653148
379906    653248
379907    640329
379908    756654
...          ...
380923    775828
380924    759320
380925    721952
380926    874323
380927    874324

[1024 rows x 1 columns]
_________
        C.COPYNO
380928    602631
380929    875643
380930    874515
380931    759224
380932    843382
...          ...
381947    753660
381948    730905
381949    641024
381950    691452
381951    799451

[1024 rows x 1 columns]
_________
        C.COPYNO
381952    769463
381953    749186
381954    892771
381955    870995
381956    871001
...          ...
382971    584115
382972    584114
382973    558002
382974    558001
382975    410946

[1024 rows x 1 columns]
_________
        C.COPYNO
382976    697517
382977    639304
382978    921547
382979    800021
382980    371602
...          ...
383995    186390
383996    186391
383997    707637
383998    593876
383999    583049

[1024 rows x 1 columns]
_________
        C.COPYNO
384000    635881
384001    528045
384002    530097
384003    639998
384004    639995
...          ...
385019    820367
385020    837790
385021    872117
385022    834420
385023    691454

[1024 rows x 1 columns]
_________
        C.COPYNO
385024    909625
385025    640232
385026    876587
385027    871704
385028    634126
...          ...
386043    898397
386044    908411
386045    908409
386046    688719
386047    633327

[1024 rows x 1 columns]
_________
        C.COPYNO
386048    756679
386049    700964
386050    763669
386051    330964
386052    186296
...          ...
387067    683399
387068     75573
387069    667056
387070     44044
387071    877651

[1024 rows x 1 columns]
_________
        C.COPYNO
387072    880834
387073    853599
387074     44047
387075    667376
387076    666453
...          ...
388091    613741
388092    634071
388093    633071
388094    631519
388095    195934

[1024 rows x 1 columns]
_________
        C.COPYNO
388096    821764
388097    844876
388098    864788
388099    197826
388100    616436
...          ...
389115    838257
389116    563405
389117    563403
389118    606768
389119    563404

[1024 rows x 1 columns]
_________
        C.COPYNO
389120    631697
389121    513911
389122    635197
389123    612495
389124    630657
...          ...
390139    639945
390140     40127
390141    840720
390142    633717
390143    823405

[1024 rows x 1 columns]
_________
        C.COPYNO
390144    631179
390145    846825
390146    909908
390147    698233
390148    875142
...          ...
391163    673535
391164    438621
391165    672906
391166    673084
391167    666295

[1024 rows x 1 columns]
_________
        C.COPYNO
391168    504426
391169    538214
391170    574662
391171    618898
391172    618922
...          ...
392187    671838
392188    671841
392189    873892
392190    873894
392191    672286

[1024 rows x 1 columns]
_________
        C.COPYNO
392192    672288
392193    873981
392194    873983
392195    671848
392196    671853
...          ...
393211    708358
393212    747734
393213    823844
393214    333864
393215    172126

[1024 rows x 1 columns]
_________
        C.COPYNO
393216    807129
393217    829962
393218    535771
393219    535770
393220    535772
...          ...
394235    190232
394236    673419
394237    813657
394238    190186
394239    190187

[1024 rows x 1 columns]
_________
        C.COPYNO
394240    190188
394241    190189
394242     52155
394243    573745
394244    873297
...          ...
395259    190502
395260    563073
395261    563070
395262    189804
395263    473132

[1024 rows x 1 columns]
_________
        C.COPYNO
395264    473131
395265    640480
395266    190503
395267    190507
395268    190508
...          ...
396283    430540
396284    430541
396285    430549
396286    410214
396287    570877

[1024 rows x 1 columns]
_________
        C.COPYNO
396288    395796
396289    428173
396290    395938
396291    370329
396292    430811
...          ...
397307    436025
397308    814768
397309    818405
397310    818649
397311    670024

[1024 rows x 1 columns]
_________
        C.COPYNO
397312    814787
397313    814790
397314    814782
397315    779367
397316    808004
...          ...
398331    890221
398332    842249
398333    190311
398334    844665
398335     43139

[1024 rows x 1 columns]
_________
        C.COPYNO
398336     79645
398337    428470
398338    808168
398339    883496
398340    651619
...          ...
399355    818458
399356    691164
399357     81507
399358    662038
399359    773771

[1024 rows x 1 columns]
_________
        C.COPYNO
399360    623849
399361    830313
399362    638108
399363    691150
399364    759547
...          ...
400379     53947
400380     53951
400381    589782
400382    585794
400383    411027

[1024 rows x 1 columns]
_________
        C.COPYNO
400384    538418
400385    344744
400386    332253
400387    445097
400388    756566
...          ...
401403    639277
401404    246880
401405    246880
401406    645536
401407    639359

[1024 rows x 1 columns]
_________
        C.COPYNO
401408    734540
401409    734539
401410    646646
401411    837001
401412    628376
...          ...
402427    831947
402428    837793
402429    841349
402430    190728
402431    190727

[1024 rows x 1 columns]
_________
        C.COPYNO
402432    579181
402433    190219
402434    190224
402435    339603
402436    428154
...          ...
403451    694736
403452    553542
403453    611795
403454    608513
403455    597977

[1024 rows x 1 columns]
_________
        C.COPYNO
403456    516575
403457    618996
403458    172244
403459    219974
403460     94639
...          ...
404475    846529
404476    331757
404477    399661
404478    788185
404479    757491

[1024 rows x 1 columns]
_________
        C.COPYNO
404480    757496
404481    851183
404482    221000
404483    399507
404484    422485
...          ...
405499    629133
405500    570932
405501    609148
405502    553396
405503    609074

[1024 rows x 1 columns]
_________
        C.COPYNO
405504    609465
405505    609103
405506    609023
405507    609475
405508    609494
...          ...
406523    825579
406524    881199
406525    657746
406526    668338
406527    913309

[1024 rows x 1 columns]
_________
        C.COPYNO
406528    913310
406529    779408
406530    808002
406531    869509
406532    725471
...          ...
407547    710300
407548     67937
407549     67944
407550     67946
407551     67948

[1024 rows x 1 columns]
_________
       C.COPYNO
407552   437854
407553   824008
407554   890753
407555   829645
407556   846354
...         ...
408571   890763
408572   191082
408573   805460
408574   873931
408575   790001

[1024 rows x 1 columns]
_________
        C.COPYNO
408576    395630
408577    623164
408578    623154
408579    838904
408580    853573
...          ...
409595    691821
409596    889274
409597    894419
409598    890544
409599    800018

[1024 rows x 1 columns]
_________
        C.COPYNO
409600    734176
409601    891453
409602     56911
409603    379024
409604    662694
...          ...
410619    887692
410620    666037
410621    664376
410622    664443
410623    648078

[1024 rows x 1 columns]
_________
        C.COPYNO
410624    709685
410625    623271
410626    723177
410627    639762
410628    567692
...          ...
411643    630799
411644    609143
411645    871515
411646    634059
411647    677597

[1024 rows x 1 columns]
_________
        C.COPYNO
411648    841196
411649    885919
411650    899427
411651    907233
411652    877897
...          ...
412667    591285
412668    610965
412669    191950
412670    668450
412671    837698

[1024 rows x 1 columns]
_________
        C.COPYNO
412672    837699
412673    707994
412674    618674
412675    590914
412676    583613
...          ...
413691    809660
413692    600828
413693    601023
413694    617467
413695    843586

[1024 rows x 1 columns]
_________
        C.COPYNO
413696    846060
413697    846244
413698    846245
413699     68794
413700    450946
...          ...
414715    192041
414716    191761
414717    535449
414718    589634
414719    569766

[1024 rows x 1 columns]
_________
        C.COPYNO
414720    192049
414721    192050
414722    680795
414723    437151
414724    580224
...          ...
415739    813423
415740    802864
415741    803075
415742    803070
415743    803064

[1024 rows x 1 columns]
_________
        C.COPYNO
415744    802987
415745    792797
415746    195857
415747    861949
415748    634509
...          ...
416763    593957
416764    579956
416765    783454
416766    897963
416767    633687

[1024 rows x 1 columns]
_________
        C.COPYNO
416768    696869
416769     47658
416770     47672
416771    796119
416772    915127
...          ...
417787    541005
417788    596251
417789    559084
417790    576440
417791    609682

[1024 rows x 1 columns]
_________
        C.COPYNO
417792    385192
417793    837852
417794    576411
417795    574665
417796    574944
...          ...
418811    733973
418812    733924
418813    734196
418814    624297
418815    740042

[1024 rows x 1 columns]
_________
        C.COPYNO
418816    705862
418817    708761
418818    639338
418819    538390
418820    629563
...          ...
419835    847286
419836    520494
419837     84374
419838     71140
419839     71176

[1024 rows x 1 columns]
_________
        C.COPYNO
419840    861048
419841    892747
419842    177437
419843    516656
419844    516657
...          ...
420859    805258
420860    171676
420861    754758
420862    503220
420863    602810

[1024 rows x 1 columns]
_________
        C.COPYNO
420864    727609
420865    494845
420866    629361
420867    494844
420868    500251
...          ...
421883     53283
421884    428773
421885     53329
421886    735122
421887    826731

[1024 rows x 1 columns]
_________
        C.COPYNO
421888     53304
421889    901186
421890    789341
421891    688488
421892    876781
...          ...
422907    851196
422908    643344
422909     50591
422910    697287
422911    669636

[1024 rows x 1 columns]
_________
        C.COPYNO
422912    721649
422913    636596
422914    852898
422915    645386
422916    645402
...          ...
423931    576081
423932     51960
423933    850265
423934    428175
423935     51943

[1024 rows x 1 columns]
_________
        C.COPYNO
423936     51905
423937     51894
423938    592488
423939     51854
423940     51823
...          ...
424955     42907
424956    782340
424957    814053
424958    545737
424959     42923

[1024 rows x 1 columns]
_________
        C.COPYNO
424960    220229
424961    355203
424962    844466
424963    355204
424964    355206
...          ...
425979    877533
425980    787341
425981    787342
425982     51689
425983    797832

[1024 rows x 1 columns]
_________
        C.COPYNO
425984    186401
425985    879165
425986    648019
425987    813883
425988    628919
...          ...
427003     71626
427004     71690
427005    490322
427006     69309
427007     69310

[1024 rows x 1 columns]
_________
        C.COPYNO
427008    794426
427009    691225
427010    565015
427011    745640
427012    673225
...          ...
428027     48128
428028     48159
428029    133480
428030     48792
428031     48060

[1024 rows x 1 columns]
_________
        C.COPYNO
428032     48084
428033     64362
428034    456971
428035     48409
428036     48428
...          ...
429051    192789
429052    570141
429053    738882
429054    741455
429055    596094

[1024 rows x 1 columns]
_________
        C.COPYNO
429056    613705
429057    614588
429058    532662
429059    570734
429060    566430
...          ...
430075    638055
430076    865656
430077     55821
430078     55825
430079    285641

[1024 rows x 1 columns]
_________
        C.COPYNO
430080    811876
430081     55862
430082    880302
430083    820306
430084    830787
...          ...
431099    828403
431100    603515
431101    605322
431102    782130
431103     53417

[1024 rows x 1 columns]
_________
        C.COPYNO
431104  824674.0
431105  828471.0
431106  781943.0
431107  781942.0
431108  815990.0
...          ...
432123  609051.0
432124  605028.0
432125  613102.0
432126  613478.0
432127  617474.0

[1024 rows x 1 columns]
_________
        C.COPYNO
432128    628705
432129    658150
432130    673519
432131    656392
432132    662333
...          ...
433147    824632
433148    827016
433149    827018
433150    824640
433151    824641

[1024 rows x 1 columns]
_________
        C.COPYNO
433152    824642
433153    824643
433154    827019
433155    827021
433156    827023
...          ...
434171    910197
434172     51992
434173     52023
434174    616402
434175     52054

[1024 rows x 1 columns]
_________
        C.COPYNO
434176    834453
434177    840347
434178     52110
434179     52124
434180    827562
...          ...
435195    862176
435196    797012
435197    614119
435198    875697
435199    519544

[1024 rows x 1 columns]
_________
        C.COPYNO
435200    682224
435201    691430
435202    681242
435203    807932
435204    779057
...          ...
436219    561735
436220    795470
436221    199051
436222    374237
436223    740904

[1024 rows x 1 columns]
_________
        C.COPYNO
436224    740518
436225    698318
436226    734467
436227    571053
436228    730912
...          ...
437243    878312
437244    653419
437245    795504
437246    532755
437247    818839

[1024 rows x 1 columns]
_________
        C.COPYNO
437248    837799
437249    844839
437250    628384
437251    879426
437252    783370
...          ...
438267    616521
438268    616522
438269    616483
438270    616485
438271    616504

[1024 rows x 1 columns]

_________
        C.COPYNO
438272    616506
438273    616508
438274    616511
438275    876240
438276    876268
...          ...
439291     55383
439292     55385
439293     55418
439294     55430
439295     55458

[1024 rows x 1 columns]
_________
        C.COPYNO
439296     55490
439297     55524
439298     55538
439299     55540
439300    167934
...          ...
440315    576316
440316    576292
440317    576298
440318    576286
440319    639778

[1024 rows x 1 columns]
_________
        C.COPYNO
440320    645731
440321    594471
440322    587650
440323    613949
440324    613930
...          ...
441339     55980
441340     56005
441341     56025
441342     56044
441343     75906

[1024 rows x 1 columns]
_________
        C.COPYNO
441344     75908
441345     75909
441346     75910
441347     75912
441348    500910
...          ...
442363    186589
442364    566485
442365    198433
442366    198409
442367    327067

[1024 rows x 1 columns]
_________
        C.COPYNO
442368    332096
442369    309126
442370    340673
442371    548802
442372    341805
...          ...
443387    837064
443388    907776
443389     56620
443390     56596
443391     56599

[1024 rows x 1 columns]
_________
        C.COPYNO
443392     56598
443393     56600
443394     56540
443395     56543
443396     56546
...          ...
444411    220216
444412    228409
444413    505163
444414    186105
444415    177712

[1024 rows x 1 columns]
_________
        C.COPYNO
444416    177713
444417    590226
444418    590227
444419    180971
444420    342204
...          ...
445435    782327
445436    648066
445437    672185
445438    881340
445439    879903

[1024 rows x 1 columns]
_________
        C.COPYNO
445440    664979
445441    905027
445442     47600
445443    476292
445444    476291
...          ...
446459     54670
446460     54912
446461     54916
446462     80743
446463     82018

[1024 rows x 1 columns]
_________
        C.COPYNO
446464     53634
446465     53635
446466     53638
446467     53647
446468     53651
...          ...
447483    600736
447484    551705
447485    600734
447486    600738
447487    600740

[1024 rows x 1 columns]
_________
        C.COPYNO
447488    600741
447489    600744
447490    890853
447491    409295
447492    892714
...          ...
448507     56350
448508     83846
448509    370186
448510    364614
448511    364619

[1024 rows x 1 columns]
_________
        C.COPYNO
448512     76308
448513     76327
448514     76327
448515     76374
448516     76499
...          ...
449531    730637
449532    730634
449533    730632
449534    730640
449535    730639

[1024 rows x 1 columns]

In [2]:
import pandas as pd

df = pd.read_csv(
        '../data/copies.txt',
    encoding = "ISO-8859-1",
    sep='|',
    engine='python',
    doublequote=True
)

df.columns = df.columns.str.replace('|','')
df.columns = df.columns.str.replace("''",'|')
df.columns = df.columns.str.replace("'","")
columns = df.columns.str.split("|")[0]
df.columns = [("data")]

new_df = df['data'].str.split(pat="|", expand=True)
df[columns] = new_df.iloc[:,:9]
df = df.iloc[:,1:10]

/opt/app/.venv/lib/python3.7/site-packages/ipykernel_launcher.py:11: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  # This is added back by InteractiveShellApp.init_path()

In [3]:
df.set_index('C.COPYNO', inplace=True)
df.sort_values('C.COPYNO')
df

,T.TITLENO,C.TITLE,T.MEDIUM,"A.SNAMEDECODE(A.FNAME,NULL,NULL,,A.FNAME)",T.PRCLASSMARK,C.SHELFMARK,C.BARCODE,L.LOCLD
C.COPYNO,,,,,,,,
228312,171663,La audiometria del adulto y del nino,IMPR,"Quiros, Julio B. De",WV270,WV270/0053240,0053240,Biblioteca San Fernando - Cali. Univalle.
78769,52740,Enciclopedia britanica,IMPR,"Yust, Walter",AE5,AE5E56 v10,0193523,Biblioteca San Fernando - Cali. Univalle.
78774,52740,Enciclopedia britanica,IMPR,"Yust, Walter",AE5,AE5E56 v11,0193522,Biblioteca San Fernando - Cali. Univalle.
78777,52740,Enciclopedia britanica,IMPR,"Yust, Walter",AE5,AE5E56 v12,0193521,Biblioteca San Fernando - Cali. Univalle.
78779,52740,Enciclopedia britanica,IMPR,"Yust, Walter",AE5,AE5E56 v13,0193520,Biblioteca San Fernando - Cali. Univalle.
...,...,...,...,...,...,...,...,...
367136,334070,Don Marco Fidel Suarez,IMPR,"Galvis Salazar, Fernando",,928 S939g e2,0042785,Biblioteca Mario Carvajal - Melendez - Cali. U...
366494,334070,Don Marco Fidel Suarez,IMPR,"Galvis Salazar, Fernando",,928/0172096,0172096,Biblioteca Mario Carvajal - Melendez - Cali. U...
57269,38373,La Europa del siglo XIX y la idea de nacionalidad,IMPR,"Weill, Georges",,940.28 W422,0043244,Biblioteca Mario Carvajal - Melendez - Cali. U...
840951,340997,"La republica espanola y la guerra civil, 1931-...",IMPR,"Jackson, Gabriel",,946.081 J12r v3,0467186,Biblioteca Sede Caicedonia - Univalle
396954,367366,Estructuras andinas del poder,IMPR,"Rostworowski, Maria",,985.01 R839e e1,0187572,Biblioteca Mario Carvajal - Melendez - Cali. U...

In [4]:
df.dtypes

T.TITLENO                                    object
C.TITLE                                      object
T.MEDIUM                                     object
A.SNAMEDECODE(A.FNAME,NULL,NULL,,A.FNAME)    object
T.PRCLASSMARK                                object
C.SHELFMARK                                  object
C.BARCODE                                    object
L.LOCLD                                      object
dtype: object

In [5]:
df.describe()

,T.TITLENO,C.TITLE,T.MEDIUM,"A.SNAMEDECODE(A.FNAME,NULL,NULL,,A.FNAME)",T.PRCLASSMARK,C.SHELFMARK,C.BARCODE,L.LOCLD
count,450450,450450,450450,450450,450450,450450,450450,450450
unique,283783,249607,51,153466,16956,443756,441869,46
top,399781,Bioquímica,IMPR,,658,E-BOOK,,Biblioteca Mario Carvajal - Melendez - Cali. U...
freq,174,394,375090,1662,4311,91,5671,310717

# Cleaning Data

##### https://towardsdatascience.com/how-to-check-for-missing-values-in-pandas-d2749e45a345

In [6]:
df.isna().any().any()

False

In [7]:
df.isnull().any().any()

False

In [8]:
df.isna().sum().sum()

0

In [9]:
df.isna().sum()/(len(df))*100

T.TITLENO                                    0.0
C.TITLE                                      0.0
T.MEDIUM                                     0.0
A.SNAMEDECODE(A.FNAME,NULL,NULL,,A.FNAME)    0.0
T.PRCLASSMARK                                0.0
C.SHELFMARK                                  0.0
C.BARCODE                                    0.0
L.LOCLD                                      0.0
dtype: float64

In [10]:
df.loc[:, df.isnull().any()].columns

Index([], dtype='object')

In [11]:
df.dropna(subset=["T.TITLENO"])

,T.TITLENO,C.TITLE,T.MEDIUM,"A.SNAMEDECODE(A.FNAME,NULL,NULL,,A.FNAME)",T.PRCLASSMARK,C.SHELFMARK,C.BARCODE,L.LOCLD
C.COPYNO,,,,,,,,
228312,171663,La audiometria del adulto y del nino,IMPR,"Quiros, Julio B. De",WV270,WV270/0053240,0053240,Biblioteca San Fernando - Cali. Univalle.
78769,52740,Enciclopedia britanica,IMPR,"Yust, Walter",AE5,AE5E56 v10,0193523,Biblioteca San Fernando - Cali. Univalle.
78774,52740,Enciclopedia britanica,IMPR,"Yust, Walter",AE5,AE5E56 v11,0193522,Biblioteca San Fernando - Cali. Univalle.
78777,52740,Enciclopedia britanica,IMPR,"Yust, Walter",AE5,AE5E56 v12,0193521,Biblioteca San Fernando - Cali. Univalle.
78779,52740,Enciclopedia britanica,IMPR,"Yust, Walter",AE5,AE5E56 v13,0193520,Biblioteca San Fernando - Cali. Univalle.
...,...,...,...,...,...,...,...,...
367136,334070,Don Marco Fidel Suarez,IMPR,"Galvis Salazar, Fernando",,928 S939g e2,0042785,Biblioteca Mario Carvajal - Melendez - Cali. U...
366494,334070,Don Marco Fidel Suarez,IMPR,"Galvis Salazar, Fernando",,928/0172096,0172096,Biblioteca Mario Carvajal - Melendez - Cali. U...
57269,38373,La Europa del siglo XIX y la idea de nacionalidad,IMPR,"Weill, Georges",,940.28 W422,0043244,Biblioteca Mario Carvajal - Melendez - Cali. U...
840951,340997,"La republica espanola y la guerra civil, 1931-...",IMPR,"Jackson, Gabriel",,946.081 J12r v3,0467186,Biblioteca Sede Caicedonia - Univalle
396954,367366,Estructuras andinas del poder,IMPR,"Rostworowski, Maria",,985.01 R839e e1,0187572,Biblioteca Mario Carvajal - Melendez - Cali. U...

# Save data to another file

In [12]:
df.to_csv('modified.csv', index=True, sep='*')